### ISSUE TITLE
Setup CI/CD and new deployment domain

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#100]
Our project has come far from how it used to be with a lot of changes and new components.

To show all newly added components and design changes, I think we should create it as a dummy portfolio. To make it clear, let's use all the components in the demo deploy build.

This would:
- keep the demo updated with all new features.
- since most people like to see the demo before using a project (myself included), this will show all possibilities of our project.

(This would also mean that you would have to move your personal deployment of the project to a private or other repo)
Let me know what you think about this.

**Comment by saadpasta** [comment]
@kartik918 currently I am using another repo for `saadpasta.github.io`, not developerFolio. 

And I agree with you we should create a demo project so anyone who need to see demo can view all the possible components with DeveloperFolio and we should integrate CI/CD so we manually don't have to make a build and deploy it every time. 
We Could use Github Pages for our Demo and `gh-pages` branch for our build and the URL for our demo would be `saadpasta.github.io/developerFolio`. ✌️
What do you think.

**Comment by kartik918** [comment]
Sounds good to me, we could use ``master`` branch for all new commits and merge it to ``gh-pages`` when there a certain amount of new changes introduced to master. This way it won't have to update again and again for minor changes.

Setting up CI for this would be a great boost to workflow. 

P.S your current build has missing components so you might want to look into that.

**Comment by naveen521kk** [comment]
@saadpasta I found that you have deployed this in https://developerfolio.js.org/ . Please check out the issue. Rebuild the site again as there was a issue with it.

**Comment by saadpasta** [comment]
@naveen521kk looking into it

**Comment by naveen521kk** [comment]
Can we user [versel](https://vercel.com/docs/v2/git-integrations/vercel-for-github) CI/CD. It has great features and is free. It deploys all PR automatically and would be useful. What do you think @saadpasta and @kartik918 ?

**Comment by kartik918** [comment]
I agree, Versel is great for CD. I would suggest @saadpasta to take up this issue.

**Comment by saadpasta** [comment]
@kartik918 Done.

**Comment by naveen521kk** [comment]
@saadpasta I will make a PR to gh-pages branch with Adding all the components. Let's use it as our deploy instead of [https://saadpasta.github.io](https://saadpasta.github.io). And then we can use js.org domain.

**Comment by naveen521kk** [comment]
And once this PR for [js.org](https://github.com/js-org/js.org/pull/4031) goes live we would have [https://developerfolio.js.org/](https://developerfolio.js.org/). And @saadpasta what about adding a CI to this project?

**Comment by naveen521kk** [comment]
And now our deployment is live at https://developerfolio.js.org/. Further @saadpasta We would need to add a CI for automatically deployment of master.👍😀

**Comment by saadpasta** [comment]
@naveen521kk Thanks for taking care. Really appreciate it.
I'll set up the CI/CD for this whenever something is pushed to master we create a build and pushed it to our branch on gh-pages

**Comment by naveen521kk** [comment]
Are we done with CI? @saadpasta  Further I think we can use Versel for Deploying our pull requests.

**Comment by saadpasta** [comment]
I was thinking of Github Actions. What do you say

**Comment by naveen521kk** [comment]
I think @saadpasta for a full deploy with all component we would need to use an Environment variable for that. Especially for Open source section.

**Comment by kartik918** [comment]
@saadpasta @naveen521kk The current deployment branch link in our repo's description has partially broken elements with Naveen's bio lol. We should look into it and revert it to Saad's or just make it neutral. 

As in add "Your name, Your bio here in 2-3 lines, Your work experience" etc. What do you guys think and we should address this ASAP.

**Comment by naveen521kk** [comment]
I will take up this and update this with Saad'd and soon write something neural.

**Comment by kartik918** [comment]
Yep but let's wait for PRs that are being worked on to merge first so they don't have issues while getting it merged. We can update the deployed one with the neutral info though just not update master branch right now. Or keep it like before using Saad's info and then update afterwards.

**Comment by naveen521kk** [comment]
Versel is doing its work good. But does it deploy our `master` branch to `gh-pages`? Deploying it so is much necessary. If it doesn't we should come out with a script using Github Actions to do that. Or if f wanted we can also use Travis CI. What do you think about this @saadpasta ?

**Comment by naveen521kk** [comment]
@saadpasta @kartik918 Can we add https://github.com/JamesIves/github-pages-deploy-action to our this for deploying master branch? Or, can we use Travis CI to do it?

**Comment by kartik918** [comment]
It's just two CLI commands to run so we can either use our own ``action.yml`` file or get an action from the marketplace. I'm good either ways as long as it gets the job done perfectly.

**Comment by naveen521kk** [comment]
Um. We have some issues in `Portfolio.js`. We want a full deploy with all the component and its nearly _impossible_ to set the Github Personal Access tokens and commit to master. Its required that it is an environmental variable. @kartik918

**Comment by kartik918** [comment]
It's not *impossible*. You can setup secrets in the settings of a repo and that access is with Saad only.

Not sure what you mean by it would be impossible to achieve.

**Comment by naveen521kk** [comment]
We have to make a commit in master switching Github repo card variable to a environment variable, for the ease of deploy. If you, know how about in setting up Github Action you can set it up. @kartik918 

Furher, Sorry for using _impossible_.

**Comment by kartik918** [comment]
It's alright. I know what you mean by setting up the variable but like I said before, only admin can set secrets and stuff in the repo which is @saadpasta 's domain. So nothing we can do on this.

**Comment by saadpasta** [comment]
@kartik918 @naveen521kk I was busy. We have Eid Here in Pakistan. I am working on it

**Comment by kartik918** [comment]
No hurries @saadpasta , Eid Mubarak!

**Comment by naveen521kk** [comment]
Eid Mubarak!!

**Comment by saadpasta** [comment]
Fixed Vercel added and Github Action added to deploy to our Github pages domain. 
Please check Github Action Tab

**Comment by saadpasta** [comment]
@kartik918 @naveen521kk 
Codacy has also been removed
