### ISSUE TITLE
Open Source Project did'nt show

### ISSUE THREAD

**Issue by pearces17** [saadpasta/developerFolio#101]
I already put the token and my GH username but none of my repos shown on the web app. Any idea to solve this?

**Comment by naveen521kk** [comment]
@pearces17 Where has you hosted it? And did you follow the steps in Readme File exactly? And also have you converted it to base64? Please check your console for any logs and tell. Any detailed info would be appreciated 😊.

**Comment by kartik918** [comment]
If you could send a copy of your Github section of ``portfolio.js``, it'd help understand your problem better,

Just send a copy of this section from your local clone,

```javascript
 const openSource = {
  /* Your Open Source Section to View Your Github Pinned Projects */
  /* To know how to get github key look at readme.md */
  
  githubConvertedToken: "Your Github Converted Token",
  githubUserName: "Your Github Username"
};
```

**Comment by pearces17** [comment]
@naveen521kk i run it on local machine, i'd exactly as Readme.md including convert my token to base64 format, here's that i found on console  :

> ./src/containers/projects/Projects.js
  Line 15:6:  React Hook useEffect has a missing dependency: 'getRepoData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

@kartik918 here's the snippet , 
`const openSource = {
  githubConvertedToken: "MDI5MTZmYTgyYTE4Yzk5ZDZhNjY4N2E1YTRmMmI5M2ZiZGM2NzM4YQ==",
  githubUserName: "pearces17"
};
`

thank you for your response g1uys, that would help me a lot ❤️

**Comment by kartik918** [comment]
You can try ``// eslint-disable-next-line react-hooks/exhaustive-deps`` before the violating line and let me know the result here @pearces17 . 

Thanks for reporting this, we'll look further into it. (could be related to #62)

**Comment by pearces17** [comment]
@kartik918 just try what you told, but nothing happen still

**Comment by pearces17** [comment]
it's done, it's only doesnt work on development view , but work perfectly after hosted on some hosting platform. Thankyou collaborators, for your resopnse

**Comment by kartik918** [comment]
Deleted your GH token comment for privacy.

**Comment by FlyingBackdoor** [comment]
I am also facing this issue. It is not working even after deployment

Here is the log related to project section
`./src/containers/projects/Projects.js
  Line 18:6:  React Hook useEffect has a missing dependency: 'getRepoData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/containers/profile/Profile.js
  Line 54:6:  React Hook useEffect has a missing dependency: 'getProfileData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`
