### ISSUE TITLE
Favicon icon for all views(mobile, ipads, shortcuts)

### ISSUE THREAD

**Issue by BharatKammakatla** [saadpasta/developerFolio#103]
Since most of the traffic is on mobile sites, it would be good to add more favicon options to display even in mobile & ipad address bar, etc. It is a simple process as specifed in https://realfavicongenerator.net. 
> `suggestion`

**Comment by kartik918** [comment]
Thanks for the suggestion! Would you like to take this up as your first contribution @BharatKammakatla ?

**Comment by BharatKammakatla** [comment]
Sure, will work on it and send PR.

**Comment by kartik918** [comment]
Fixed in #106
