### ISSUE TITLE
Running into CORS error

### ISSUE THREAD

**Issue by TejasPanambur** [saadpasta/developerFolio#105]
![image](https://user-images.githubusercontent.com/40962268/80657280-31295d80-8a51-11ea-94c6-57ed99fa4000.png)

**Comment by naveen521kk** [comment]
@TejasPanambur  Your website works well for me. Please check again.

**Comment by kartik918** [comment]
I see no more activity on this issue, if it still persists, feel free to reopen.

**Comment by AdamLBS** [comment]
Hello, i also have the same issue on https://admlbs.fr on mobile and computer
