### ISSUE TITLE
Use socialMediaLinks.github in href of MORE PROJECTS button

### ISSUE THREAD

**Issue by viniciusbds** [saadpasta/developerFolio#109]
This is a suggestion.

I think the href of  [`MORE PROJECTS`](https://github.com/saadpasta/developerFolio/blob/master/src/containers/projects/Projects.js#L79) could use the [socialMediaLinks.github](https://github.com/saadpasta/developerFolio/blob/master/src/portfolio.js#L19) content

**Comment by kartik918** [comment]
Good catch, thanks!
