### ISSUE TITLE
Update Portfolio.gif in Readme.

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#114]
As recently there have many changes on the site I think its time for us to update Protoflio.gif in ReadMe file. This would help visitors to see the latest Version of the project.

**Comment by naveen521kk** [comment]
@kartik918 DO you know how to upload it to GitHub user content? It doesn't allow me to upload here even! ( Its more than 10 MB. )

**Comment by kartik918** [comment]
Downscale the quality, but don't reduce the framerate. You can use an online converter.

**Comment by naveen521kk** [comment]
Here's the gif.
![optimize](https://user-images.githubusercontent.com/49693820/81284284-8aaa1180-907b-11ea-8070-dc64ae563400.gif)
I will make a PR with this.

**Comment by kartik918** [comment]
I think you recorded it with a smaller viewport, the proficiency graphic isn't displayed. Can you record it with that displayed? Will make the intro gif more interesting.

**Comment by naveen521kk** [comment]
I couldn't find it even on full screen of my PC. Check out https://developerfolio.js.org/. If it is missing there we found a bug.

**Comment by naveen521kk** [comment]
Have expected like the screenshot below while creating it? If yes I found a fix for it.
![skills](https://user-images.githubusercontent.com/49693820/81291735-fa25fe00-9087-11ea-98de-c3228300ceaf.PNG)

**Comment by kartik918** [comment]
Why is this not working though? Did you find the cause for it?

**Comment by naveen521kk** [comment]
This is because of this line in CSS file.
```CSS
@media (max-width: 1456px) {
    .skills-bar {
        line-height: 4rem;
    }
    .skills-image {
        display: none;
        order: 2;
    }
}
```
Because of `display: none;` in media query.

**Comment by naveen521kk** [comment]
This is the final of portfolio.gif.
![optimized-final](https://user-images.githubusercontent.com/49693820/81296489-999abf00-908f-11ea-9442-75e8f0ecf65d.gif)
