### ISSUE TITLE
Serve images in next-gen formats

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#118]
The images in the assets folder are in PNG or JPEG. Those images should be converted into next-gen formats like JPEG 2000, JPEG XR, or WebP for faster page loading time and improving the [PageSpeed score.](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeveloperfolio.js.org%2F&tab=mobile)

**Comment by garimasingh128** [comment]
Hello @naveen521kk Can you elaborate about this issue? Do we only have to convert the assets to next-gen formats or any other config is required in the project?

**Comment by saadpasta** [comment]
@garimasingh128 Read this article this would help https://web.dev/uses-webp-images/

**Comment by naveen521kk** [comment]
@garimasingh128 What I actually meant was to convert all the images from the `assets` folder to `webp`  or `JPEG 2000` or `JPEG XR` formats. These would decrease the page load time and increase the score in [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeveloperfolio.js.org%2F&tab=mobile).

**Comment by aashutoshrathi** [comment]
Can I take this up?

**Comment by kartik918** [comment]
Hey @aashutoshrathi this has been fixed in #122 and should've been assigned and mentioned here, sorry. But you can look into other good first issues we have. Looking forward to seeing your contributions!

**Comment by aashutoshrathi** [comment]
Sure. I'll hope to another one.
Thanks for the heads-up .

**Comment by naveen521kk** [comment]
@kartik918 I had closed the issues which has been fixed by #122 . And this has not yet been fixed so reopening and assigning to @aashutoshrathi.

**Comment by kartik918** [comment]
@aashutoshrathi are you still working on this? Thanks.

**Comment by aashutoshrathi** [comment]
Will pick it, this week.

**Comment by aashutoshrathi** [comment]
@naveen521kk Should I convert them once and for all? Or we need an script?

**Comment by naveen521kk** [comment]
Its enough to convert it all at once. We no need any script for that. @aashutoshrathi
