### ISSUE TITLE
Issue in github secret token

### ISSUE THREAD

**Issue by prudhvir3ddy** [saadpasta/developerFolio#119]
the part of github repos fetching interested me in this project. so i had a look to implement in my portfolio 

and found out you mentioned to get encrypted key using btoa() which can be easily reverted back to atob() and and can be used  by third members.

i want you to do this way, which can favour deployment also..  

right now, i saw you are having two projects, this is for react-code and build code in different projects 

how about having only one project with username.github.io as it wants master code as build code

-> have a develop branch where your react code comes

whenever you do a push run a ci-script which adds github key at runtime from env vars or secrets with more security and produces build code in master branch

**Comment by saadpasta** [comment]
@prudhvir3ddy Thanks for taking an interest. Actually we have clearly mentioned in the docs that you should not select any scope while generating a token so a simple token can only access the public info and won't cause any damage this is done for beginner ease. 

Actually saadpasta.github.io is my personal portfolio and it's just for the demo I am thinking to create a website for developerFolio with all demo's and other pro's and cons and all of the components currently my portfolio is a little different for what developerFolio is offering and my portfolio has some missing components also.

**Comment by prudhvir3ddy** [comment]
@saadpasta oh okay. cool then you can close this issue.

**Comment by prudhvir3ddy** [comment]
@saadpasta also, i am taking some of your code and customising it to my usecase. as my design interest is little close to this site and want some changes to mine. 

so i included in this way i my readme.md. should i give credits anywhere else ?

<img width="1163" alt="Screenshot 2020-05-09 at 9 25 37 PM" src="https://user-images.githubusercontent.com/20471162/81478547-de635900-923b-11ea-8d3b-e1af5f1b01eb.png">

**Comment by naveen521kk** [comment]
@prudhvir3ddy Further we partly made it with https://developerfolio.js.org. We just need to set up a CI.
CC. @saadpasta

**Comment by saadpasta** [comment]
> @saadpasta also, i am taking some of your code and customising it to my usecase. as my design interest is little close to this site and want some changes to mine.
> 
> so i included in this way i my readme.md. should i give credits anywhere else ?
> 
> <img alt="Screenshot 2020-05-09 at 9 25 37 PM" width="1163" src="https://user-images.githubusercontent.com/20471162/81478547-de635900-923b-11ea-8d3b-e1af5f1b01eb.png">

That's perfectly okay. Good luck with your portfolio
