### ISSUE TITLE
Open Source Section minor UI update

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#123]
The open-source section in the portfolio has more space and alone font-size is bigger. See the screenshot below.
![openSource-section](https://user-images.githubusercontent.com/49693820/81534994-9dc42680-9386-11ea-84bb-e369258828b7.PNG)
The font size of the heading should be reduced. Further, the icon size of the repo should be increased. Using emoji function in description of the 
Repo would ensure uniform rendering of emoji. Refer #84.

**Comment by sparsh-99** [comment]
Closes #156

**Comment by kartik918** [comment]
Closed by #183
