### ISSUE TITLE
Remove src/assests/font-awesome folder

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#126]
The folder located at `src/assests/font-awesome` has many issues in Codacy and as well it is not *required*. I also *found* there is a link to font-awesome CSS in `index.html` and that would do. So instead of importing the whole font-awesome using a *CDN* is better.

**Comment by naveen521kk** [comment]
What do you think @saadpasta and @kartik918 about this?

**Comment by kartik918** [comment]
Yeah, if we're already using CDN, we don't need fa. You might want to check if it's being used somewhere since there must be a reason for it to be locally served in the first place. 

This will optimize repo size by a little bit too.

**Comment by naveen521kk** [comment]
I tried *removing* it. It just showed one error. I removed the line that showed that error in `src/index.js`. After that I updated `index.html` with latest CDN link. ( There was a old version linked). After everything, I got no error and all icon rendered properly. Is there anything else that depends on it? @kartik918 @saadpasta

**Comment by kartik918** [comment]
Open a PR for it and we can check the changes @naveen521kk
