### ISSUE TITLE
Add Work Experience Section

### ISSUE THREAD

**Issue by HenryHengZJ** [saadpasta/developerFolio#131]
## Summary
Hi all thanks for the awesome project and the supporting community here. I was wondering can we add a section of work experience just like https://bchiang7.github.io. If yes, I would love to contribute to that.

### What's new?
Adding a new section called WorkExperience that showcase past experiences with timeline.

### Motivation
As an electronics engineer with no formal CS background, I think it's important to add my past work experiences to showcase my other skillsets.

Let me know what you guys think!

**Comment by saadpasta** [comment]
@HenryHengZJ That's really a great idea. But first, we need some sketch or design for this section.
@kartik918

**Comment by saadpasta** [comment]
Or should we use https://bchiang7.github.io/ experience section design

**Comment by HenryHengZJ** [comment]
I have a relatively simple design like this:
![image](https://user-images.githubusercontent.com/26460777/82365252-53871900-9a08-11ea-9492-a4b76dafa713.png)

**Comment by saadpasta** [comment]
@HenryHengZJ That's a really cool design I love it. 
@kartik918 @naveen521kk what do you guys say.

**Comment by saadpasta** [comment]
This also matches with our theme

**Comment by kartik918** [comment]
Hey @HenryHengZJ, thanks for this idea and the mock.

I like the work horizontal card design but the overall section still could use a fresh look.
Since most of our sections follow the same pattern, let's break the norm with this one!

Unfortunately I'm pretty busy this week so I can't promise mocks "ASAP" but if you find any inspiration or come up with some different design ideas, I'd love to see them.

**Comment by naveen521kk** [comment]
@HenryHengZJ, thanks for this idea and the *mock*. I think it is a *really* great addition to this project. I accept with @kartik918 on changing the theme. So lets make it as a new *component* to our site.

**Comment by HenryHengZJ** [comment]
Hey guys I came up with a cardview based design:

https://codepen.io/henryhengzj/pen/vYNvjJY

![image](https://user-images.githubusercontent.com/26460777/82445214-54698a80-9a9c-11ea-9ad1-681376a00215.png)

**Comment by kartik918** [comment]
I like this design but I have a few changes in mind.

- Let's make the edges less round so it fits more with the other card components.

- Switch card background to a brand color of the place they've worked at. This would solve the problem of low res images, background noise and looks better in general.

I made the above design changes while playing with the code pen:

![image](https://user-images.githubusercontent.com/48270786/82452436-dffb0f80-9acc-11ea-8d19-af9c53073f65.png)

The brand color ideally should be extracted from the image set by the user to reduce manual configurations and make it easier to use. We could use a script for extracting prominent colors from the images or we could keep it manually. Would appreciate more thoughts on this.

Also do you want to take this up @HenryHengZJ or we can assign it to someone else.

**Comment by HenryHengZJ** [comment]
@kartik918 Thanks for the suggestion and improvement. I am happy to take this up as my first open-source contribution 🙌 I know there is a library that extracts the prominent color of an image https://github.com/lokesh/color-thief.

**Comment by kartik918** [comment]
Alright I'm assigning this to you. If you need help or get stuck somewhere, feel free to ask so we can deliver this smoothly.

Some stuff to keep in mind while working on this component, 

- keep the component independent, as in independent JS, HTML and CSS like other components you must have checked out in the repo.

- update portfolio.js with minimal user information for the component like:
``Name of company,
 Dates,
 Description,
 Image URL
``

- in the end, update README with the relevant stuff about it's config that you've added in this component.

I tested the library for the point you made about prominent whites on an image. The library is smart enough to not pick up whites on any image I tested, it picks up the next most prominent color other than white which is good for our use! 

This would be a cool addition to the project and having the library utility installed, we can have further components that pick up accents from images. Let's get started!

**Comment by HenryHengZJ** [comment]
@kartik918  Should I install the library with npm or load it from CDN?

**Comment by naveen521kk** [comment]
Installing through `npm` is better. As our codebase already has many external requests it is better to serve it locally (Also for *offline* testing). So, I recommend installing through `npm` instead of `cdn`.

**Comment by kartik918** [comment]
NPM

**Comment by naveen521kk** [comment]
Fixed in #136
