### ISSUE TITLE
Hosting with GitHub pages?

### ISSUE THREAD

**Issue by awarmfastbear** [saadpasta/developerFolio#132]
**Describe the bug**
The README.md describes being able to host this with GitPages, but as I understand it that is just for static HTML pages. Is there a step missing in the ReadMe that allows you to build and minify the site into a static build folder so you don't need a NodeJS backend to run it?

I guess `npm build` should work but if I build and push those built files into a repo and put a Github page in front of them I get 404s on the JS and CSS files as they aren't accessible.

**Comment by naveen521kk** [comment]
You would need to *change* the `homepage` in `package.json` to your site path in your case it is `https://awarmfastbear.github.io/myportfolio` or simply `/mypotfolio`. On doing so the site builds your site with that path and you would not get  a *404 error*. For more information about this check out this [doc](https://create-react-app.dev/docs/deployment/#github-pages) from Create React App. By default it assume you are *hosting* it in the root of the domain, so you get those *errors*.

Further, for deploying your site in GitHub Pages just type `npm deploy` in your terminal. Before that you would to install dependencies by typing `npm install`. Doing this deploys *production* build to `gh-pages` branch of your repo and your site goes *live*.

**Comment by kartik918** [comment]
We should update this information in our README so others don't get confused either.
