### ISSUE TITLE
Build failing on windows

### ISSUE THREAD

**Issue by th3c0d3br34ker** [saadpasta/developerFolio#139]
**Describe the bug**

**To Reproduce**
1. Go to build 
2. Click on ... just build it.
3. Scroll down to: no where to scroll
./src/components/talkCard/TalkCard.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/components/talkCard/TalkCard.css)

**Expected behavior**
Expected a successful build.

**Is this responsiveness Issue**
NO

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser All
 - Version All

**Additional context**
src/components/talkCard/TalkCard.css
changing '\\' to '/' would solve the issue in line 8 of the above file.

**Comment by saadpasta** [comment]
Is npm start working correctly

**Comment by th3c0d3br34ker** [comment]
yes

**Comment by th3c0d3br34ker** [comment]
No

**Comment by naveen521kk** [comment]
Could you please take a screenshot of the terminal output. It would help in debugging. I use windows 10, I don't get these error. Also, make sure you check you haven't edited anything and just run. @th3c0d3br34ker

**Comment by th3c0d3br34ker** [comment]
I just cloned it again and tried to run it... I noticed I had run 'npm audit fix' other than that...
No, I haven't edited anything before running it... However i have attached a screenshot
![image](https://user-images.githubusercontent.com/60807938/82749441-e76d3200-9dc6-11ea-9e90-434682e5f2d6.png)

**Comment by naveen521kk** [comment]
Try out with  `npm install` again. Then, try out with `npm start`. It should work I think.

**Comment by th3c0d3br34ker** [comment]
the issue still persists... in all other places forward slash has been used, for sake of uniformity too...

**Comment by naveen521kk** [comment]
I don't think there is any problem with the code @th3c0d3br34ker . Try cloning it again and without _copying_ node_modules using the command **npm install**. On seeing the **screenshot**, I see that's because of node_modules and not because of code . And if the problem continues the best would be reinstalling _Node Js_. And also, what version of npm you run?

**Comment by th3c0d3br34ker** [comment]
Yes there is nothing wrong with the code, this just a friendly suggestion its totally up to you to change it, it will work without `npm audit fix`, also in other .css files are referenced with forward slashes just for the sake of uniformity making this small change wont do any harm.
Also, great fan of this project and would like to thank @saadpasta all the contributors for this amazing project, and looking forward to dark theme toggle feature 😀. I am closing this issue, however if you want to do the proposed changes, it would be greatly appreciated.
