### ISSUE TITLE
I 'm beginner, facing issue in deployment, can you pls help me?

### ISSUE THREAD

**Issue by Abubakarmujahid** [saadpasta/developerFolio#148]
![image](https://user-images.githubusercontent.com/65970121/82936160-9a948180-9fa7-11ea-8d49-5680378fa7e1.png)

![image](https://user-images.githubusercontent.com/65970121/82936220-b13ad880-9fa7-11ea-96ca-b29114195bcd.png)

![image](https://user-images.githubusercontent.com/65970121/82936259-bc8e0400-9fa7-11ea-82f5-c4f0ca767468.png)

**Comment by naveen521kk** [comment]
This `package.json` doesn't belong to this repository. And it is more important that you use the same `package.json`. The file is available in the root of directory. I think that would solve your problem.

**Comment by Abubakarmujahid** [comment]
Thank you, can you pls guide me about where will be root of directory?

**Comment by naveen521kk** [comment]
Have you `cloned` the repository using git? Or just downloaded it. For your reference, I have added linked `package.json`.
https://github.com/saadpasta/developerFolio/blob/master/package.json
The same content should be there while deploying it.

**Comment by Abubakarmujahid** [comment]
Thanks, Ye I cloned it.

**Comment by naveen521kk** [comment]
Can this issue be closed?

**Comment by Abubakarmujahid** [comment]
yes, thank you very much
