### ISSUE TITLE
Add subPoints section in workExperiences section

### ISSUE THREAD

**Issue by AkshayCHD** [saadpasta/developerFolio#154]
First of all great work @saadpasta and all other contributors, really an awesome project.

## Summary
In the experience section, It would be great to have a functionality to add subpoints along with the general description.

### Motivation
Actually I was using the project to create my own portfolio, but some of my internships involved me working on several projects instead of one. The idea to keep all that detail in a single paragraph did not feel good, so I added a subPoints section to the workExperiences variable, and rendered a list using that.

### Additional context
![portfolio1](https://user-images.githubusercontent.com/25455546/83330506-f6635100-a2ac-11ea-9739-bade4e9b4c6f.png)

**Comment by AkshayCHD** [comment]
@saadpasta If the issue seems valid I would like to make a PR for it

**Comment by saadpasta** [comment]
@AkshayCHD It would be great to add bullet points but make sure you make that optional

**Comment by AkshayCHD** [comment]
@saadpasta PR raised

**Comment by kartik918** [comment]
@saadpasta this seems like a personal formatting choice, no? So I think the user can edit HTML to add bullets. 

But this also simplifies the process more for the user and gives more options without touching the code under the hood so I'm conflicted on my opinion haha.
