### ISSUE TITLE
Add "outward" transitions for button hover effects

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#156]
Current button hover animations work smoothly on the first half and return to their initial state instantly on the other half of the animation (i.e taking cursor off the buttons)

Adding complementary CSS `transition: ease-in 0.3s;` to the button component `.main-button` class should work.

**Comment by sparsh-99** [comment]
Hey @kartik918, what you actually want with CSS hover?
Can you please give me a brief description?
It will be very helpful in contributing.
Thanks

**Comment by kartik918** [comment]
I'm sorry if I wasn't clear enough in the description, basically what Saad mentioned in your [PR](https://github.com/saadpasta/developerFolio/pull/179#pullrequestreview-427376605). 
Check the link to his deployment of the portfolio and update the CSS transitions with it, adding `transform: translateY(-3px);` would be a plus.
Let me know if you need more information on this @sparsh-99 .
