### ISSUE TITLE
Blog Section Bug

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#157]
**Describe the bug**
There is a bug out there in Blog Section, on smaller viewports line *mobiles*. This hides the title. (*See* the Screenshot). This needed to be fixed.

**To Reproduce**
1. Open https://developerfolio.js.org/#blogs in mobile or Dev *tools*.
2. Scroll down to *Blogs* Section.
4. See error in heading part.

**Expected behavior**
A proper title with  full text should be shown!

**Is this responsiveness Issue**
YES

**Screenshots**
![bug](https://user-images.githubusercontent.com/49693820/83347349-0c6f2100-a342-11ea-81a1-d66092dcc71d.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone6/7/8
 - OS: iOS 11

**Comment by kartik918** [comment]
Cards are off center too, so this should also be fixed in this.

**Comment by saadpasta** [comment]
@naveen521kk ellipsis is being shown we have to just fix the height to hide extra content. 
We can't show a title that exceeds more than 2 lines.

**Comment by naveen521kk** [comment]
Fixed in #161
