### ISSUE TITLE
Github Repo Not Showing In Deployment

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#162]
While going to https://developerfolio.js.org/#opensource , I just found out that the section is not visible, possibly because tokens are not entered by the new CI. Check out @saadpasta .

**Comment by naveen521kk** [comment]
Also @saadpasta make Github Actions to automate releases.

**Comment by saadpasta** [comment]
@naveen521kk yeah I am also thinking of doing so

**Comment by saadpasta** [comment]
fix #164

**Comment by kartik918** [comment]
Let's add a test podcast or remove the component all together if there's nothing to show.

**Comment by saadpasta** [comment]
@kartik918 A podcast is being shown in Podcast Section

**Comment by kartik918** [comment]
Is it? Oh then it must be my blocker. We should add a warning for that.

It used to show a while back though so it's weird.

**Comment by kartik918** [comment]
Also align the warning for Twitter component too.

Could you open an issue for it?

![image](https://user-images.githubusercontent.com/48270786/83553387-be684200-a528-11ea-9df3-d94453cb4ecc.png)

**Comment by saadpasta** [comment]
@kartik918 both are Iframe I think we can't do anything in this case

**Comment by kartik918** [comment]
Let's just add a warning like the Twitter component @saadpasta ?

**Comment by naveen521kk** [comment]
I think aligning tw component is in #107

**Comment by kartik918** [comment]
Centered Twitter component looked "off", I tried it but I'm okay with it if you guys are okay with it too.
