### ISSUE TITLE
"bash: syntax error near unexpected token" while inserting generated token on btoa("your git token")

### ISSUE THREAD

**Issue by YUSRA100** [saadpasta/developerFolio#17]

**Comment by YUSRA100** [comment]
![Capture6](https://user-images.githubusercontent.com/14943888/69407888-6e155980-0d27-11ea-9442-818d2886e85c.PNG)

**Comment by saadpasta** [comment]
@YUSRA100 you have to put this Chrome Developer Console. 
Open Chrome Developer Console then write 

`btoa(your github token)`

you will get your converted token

**Comment by YUSRA100** [comment]
@saadpasta Great. The issue is resolved. Thankyou so much for the guidance, really appreciate. 
Secondly after coping the credentials to "Projects.js" the steps are a little vague for newbies like me. Could you please elaborate on how to initiate the customization or how to visualize our own page? and the "Technologies used" part is a general information from your end or do we have to use it? 
Thankyou,

**Comment by saadpasta** [comment]
@YUSRA100 I know that's why i am creating something for complete newbies that will help them just change one file to get their own customization 

Will Push it by today or tomorrow and will also update Readme.md so if you are getting stuck in that you can stop and then just change one file to get you required design

**Comment by YUSRA100** [comment]
Oh that would be perfect.
Thankyou so much.

**Comment by saadpasta** [comment]
@YUSRA100 I have updated the repo you can have a look at the readme.md

**Comment by YUSRA100** [comment]
@saadpasta Its very much understandable now, but i am still lacking for the part of visualization. Usually we run the index file to check the look of it. Here, it is not showing anything, or am i following the wrong track?

**Comment by saadpasta** [comment]
@YUSRA100 the main or root file of this project is `src/App.js`

**Comment by kartikch918** [comment]
Close the issue now as it is resolved @saadpasta.
