### ISSUE TITLE
Use Headroom for header

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#174]
## Summary
Let's add [Headroom](https://github.com/KyleAMathews/react-headroom) to use for the header.

### What's new?
Header hides while scrolling but is stickied to top when you scroll back up.

### Motivation
H E A D E R

### Additional context
This is a good and simple issue for any first time contributors but we should add this if it doesn't get taken up in a week or two.

Also, if you're working on the PR, add it to the list of dependencies in the README and link the original repo to credit the author.

**Comment by sparsh-99** [comment]
I want to work on the issue, @kartik918

**Comment by kartik918** [comment]
Okay, this issue is your now @sparsh-99

**Comment by sparsh-99** [comment]
@kartik918 , for headroom tag, I want to change HTML file. Can you please tell me where all HTML work is saved so that I can review it for the change?

**Comment by naveen521kk** [comment]
@sparsh-99 Any updates?

**Comment by sparsh-99** [comment]
@naveen521kk I started working on it. A PR will be opened within a few days.

**Comment by naveen521kk** [comment]
@kartik918 Lets wait for few more days for any new contributor. If not, we could do it.

**Comment by kartik918** [comment]
Sure! You could invite someone you know to take this up as their first issue. You can mentor them through the issue and possibly grow a new contributor!
Or we could just finish it in a bit. Right now the dark mode PR is becoming a blocker for all existing PRs which needs more attention I think.

**Comment by archit0210** [comment]
I will work on this issue @kartik918

**Comment by archit0210** [comment]
@kartik918 need help!

**Comment by kartik918** [comment]
What's the problem?

**Comment by archit0210** [comment]
@kartik918 as i was just going through the workflow i want to know that you want changes in all pages header or only front page?

**Comment by kartik918** [comment]
The portfolio is a single page application and header is a separate component.

npm install the headroom dependency I mentioned in the issue and wrap the header component inside it. Look at their docs for more help.

This should help you out!

**Comment by archit0210** [comment]
![Capture](https://user-images.githubusercontent.com/67779397/86571972-e9aed880-bf8f-11ea-8e96-9555df8c32ce.PNG)
@kartik918 i tried to do fix the header but he thing is the header is transparent so the text is there(behind the header)

**Comment by kartik918** [comment]
You can add necessary CSS to header's background.

Also why is the header so "low" from the top?

**Comment by archit0210** [comment]
that's the snapshot after scrolling

**Comment by archit0210** [comment]
![image](https://user-images.githubusercontent.com/67779397/86751456-4bd50f80-c05c-11ea-8cf8-68e3fd1cd3ce.png)
not able to import the headroom file, help me out in this

**Comment by kartik918** [comment]
Did you do `npm install react-headroom`?

After that, `import Headroom from 'Headroom'` should work.

Also, while importing modules you don't need to add '.js' at the end for es modules.

Can you open a draft PR so I can review your code and better help you out?

**Comment by archit0210** [comment]
yes i have already installed the module and also see this problem!!
![Capture](https://user-images.githubusercontent.com/67779397/86898583-86a37a00-c126-11ea-8f7a-e7b68237e566.PNG)

**Comment by kartik918** [comment]
Have you forked the repo to your account because I don't see a fork from you.

**Comment by archit0210** [comment]
yes, please check the code

**Comment by kartik918** [comment]
Can you open a draft PR with your changes please so I can give a direct review @archit0210?

**Comment by archit0210** [comment]
done

**Comment by archit0210** [comment]
check the code and help me

**Comment by archit0210** [comment]
i just changed import headroom from "headroom" to "react-headroom", and it worked!

**Comment by kartikcho** [comment]
That's great @archit0210 , I'm glad you figured out what was wrong!

**Comment by archit0210** [comment]
@kartikcho my bad!!

**Comment by kartikcho** [comment]
It's alright, everyone's learning :)
