### ISSUE TITLE
Add loading Screen to Twitter Component, Github Profile and Github Repo

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#175]
## Summary
Need to add a loading Screen in Twitter Component, Github Profile and Github Repo just because they are taking time to load and leaves a bad impression on first look. A simple Loading Screen would do. 

### What's new?
Adding loading Screen.

### Motivation
Just come up with it while visiting the site.

**Comment by naveen521kk** [comment]
I am taking up this and will make a PR.

**Comment by kartik918** [comment]
Hey @naveen521kk , look into [Spinkit](https://tobiasahlin.com/spinkit/) to create a lightweight loader. I like the 9th one in particular, it would go well with the UI I think.
