### ISSUE TITLE
token revoke

### ISSUE THREAD

**Issue by danial1021** [saadpasta/developerFolio#180]
The token in .env is destroyed when distributed on the githubpage.
In my opinion, for security reasons,
I think it's possible to delete static files from github in the process of uploading them to github page.

what should i do?

**Comment by saadpasta** [comment]
@danial1021 I am using the token both for DeveloperFolio and saadpasta.github.io. 
Github Must have reverted the token if you have pushed the end. Don't push the .env file

**Comment by danial1021** [comment]
need github_token to run the grapql.
Will the code run even if the .env file is excluded from distribution?

**Comment by naveen521kk** [comment]
Yes @danial1021 , See [gh-pages](https://github.com/saadpasta/developerFolio/tree/gh-pages). It would work.

**Comment by JaveedIshaq** [comment]
please guide in detail how to not push .env, if i delete before depoy github repos and name image not appear,
if not deleted .env before if is revoked by github

**Comment by saadpasta** [comment]
@JaveedIshaq Please put .env file in .gitignore and then create build

**Comment by naveen521kk** [comment]
Issue closed due to no conversation.
