### ISSUE TITLE
./src/components/talkCard/TalkCard.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/components/talkCard/TalkCard.css) Module not found: Can't resolve './....

### ISSUE THREAD

**Issue by naveenjujaray** [saadpasta/developerFolio#196]
./src/components/talkCard/TalkCard.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/components/talkCard/TalkCard.css)
Module not found: Can't resolve './....

**Comment by naveen521kk** [comment]
Have you ran
```sh
npm install
```
Command? Also, see if `node_modules` directory is present in current working directory.
