### ISSUE TITLE
[Safari] Switched characters on Title 

### ISSUE THREAD

**Issue by tiagodenoronha** [saadpasta/developerFolio#199]
**Describe the bug**
The username is getting the 2 last letters switched.

**To Reproduce**
1. Write your username
2. Start npm
3. Page loads with wrong name
**Expected behavior**
Same name as username

**Is this responsiveness Issue**
NO

**Screenshots**
<img width="585" alt="image" src="https://user-images.githubusercontent.com/27889458/86300032-9a685100-bbf9-11ea-9c01-eb1bda2367b2.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser: Safari
 - Version 13.1.1
**Additional context**
Happens on https://developerfolio.js.org aswell. Last name should be Pasta, but is Pasat.

**Comment by saadpasta** [comment]
That's a very weird issue I guess. Because we are just using font for the heading nothing much. 

And for DeveloperFolio in my case, it's showing the name correctly.
<img width="164" alt="Screen Shot 2020-07-02 at 10 38 10 AM" src="https://user-images.githubusercontent.com/23307811/86320360-2a38ea00-bc50-11ea-9009-cdf053e78567.png">

**Comment by tiagodenoronha** [comment]
Strangely, only happens in safari 😄 

This is on the latest version of chrome, on the same Mac.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/27889458/86341900-cd88ff80-bc4e-11ea-9754-1b741c18413a.png">

**Comment by kartik918** [comment]
We've had another recent report of a Safari issue, @tiagodenoronha if you could provide a fix for it, that'd be great!

**Comment by tiagodenoronha** [comment]
I'm not quite skilled in react or even js... don't know if I can be of much use here besides testing... :/

**Comment by kartik918** [comment]
That's okay @tiagodenoronha, filing bugs is a pretty important contribution too!

@abhishekashyap do you want to take a look at this too since it's another Safari issue.

**Comment by abhishekashyap** [comment]
I am able to reproduce the issue but will have to look at what exactly is causing this weird bug.
