### ISSUE TITLE
Hide or Disable Section

### ISSUE THREAD

**Issue by raflisboa** [saadpasta/developerFolio#204]
## Summary
A simple way to Hide or Disable Section

### What's new?
So, in my project, I don´t need Podcast section, for example. So, is there a simple way to hide or disable useless sections?

**Comment by saadpasta** [comment]
Try `hidePodcastSection` key inside podcast section object

**Comment by myounus96** [comment]
> Try `hidePodcastSection` key inside podcast section object

I tried this but not working.
![image](https://user-images.githubusercontent.com/13608139/87244719-af927a80-c458-11ea-825d-c2cee412dda6.png)

@saadpasta

**Comment by myounus96** [comment]
BTW a workaround is, we can comment the unwanted sections in `src/containers/Main.js`
![image](https://user-images.githubusercontent.com/13608139/87245109-2ed57d80-c45c-11ea-9c12-8191c70d00f5.png)

@saadpasta  @raflisboa

**Comment by raflisboa** [comment]
I've tried hidepodcast function, but it didn't work too. I'll try comment into main.js

**Comment by naveen521kk** [comment]
Will be done in #138

**Comment by kartikcho** [comment]
Seems resolved.
