### ISSUE TITLE
working fine locally but got errors after pushed to <myusername>.github.io repo

### ISSUE THREAD

**Issue by myounus96** [saadpasta/developerFolio#207]
I've checked all the open and closed issues, but didn't found any issue similar to that.

**Describe the bug**
working fine locally but got errors after pushed to `<myusername>`.github.io repo

**To Reproduce**

1. Fork and clone the [repo](https://github.com/saadpasta/developerFolio).
2. change homepage value to https://myounus96.github.io/developerFolio.
3. create a repo named myounus96.github.io, enable github pages from settings and clone it.
4. put .env having github token in root.
5. run 
    -npm install
    -npm run(its working fine locally)
    -npm run deploy
6. copy the contents from developerFolio/build and put it in root of myounus96.github.io and pushed it.
7. when go to [url](https://myounus96.github.io) got errors in console.
8. Also tried by just writing `/developerFolio` and `https://myounus96.github.io`  in `package.json` homepage key.

**Is this responsiveness Issue**
NO

**Screenshots**
console errors
![image](https://user-images.githubusercontent.com/13608139/87239165-5e1cc800-c425-11ea-8044-a37e5d9ac703.png)

From [repo](https://github.com/myounus96/myounus96.github.io) you can see everything is in place.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chrome (version 83.0.4103.116)

**Comment by saadpasta** [comment]
@msayyaf1 make sure you have changed the URL of the homepage in package.json

**Comment by myounus96** [comment]
I did that, mentioned in point 8 in steps.
And you tagged the wrong person :D

**Comment by saadpasta** [comment]
Can I have a look at your package.json

**Comment by myounus96** [comment]
here u go https://pastebin.com/iJUDxjpj

**Comment by saadpasta** [comment]
Please change your homepage URL to `https://myounus96.github.io` and then npm deploy.

**Comment by myounus96** [comment]
> Please change your homepage URL to `https://myounus96.github.io` and then run `npm deploy`.

you mean `npm run deploy`?

**Comment by saadpasta** [comment]
yeah

**Comment by myounus96** [comment]
> Please change your homepage URL to `https://myounus96.github.io` and then run `npm deploy`.
same :(
![image](https://user-images.githubusercontent.com/13608139/87242537-098a4480-c447-11ea-9a75-9c67ba5d720c.png)

**Comment by saadpasta** [comment]
Works fine here  ✌️
<img width="1440" alt="Screen Shot 2020-07-12 at 1 55 49 PM" src="https://user-images.githubusercontent.com/23307811/87242575-70a7f900-c447-11ea-82eb-afc6a2db1264.png">

**Comment by myounus96** [comment]
here is .env, if any possibility of issue with that...
![image](https://user-images.githubusercontent.com/13608139/87242581-7ac9f780-c447-11ea-8ce9-e10f1da721ac.png)

**Comment by saadpasta** [comment]
Hard Refresh @myounus96

**Comment by myounus96** [comment]
> Hard Refresh @myounus96

yeah working :D
Thanks
