### ISSUE TITLE
Guide about icons and images

### ISSUE THREAD

**Issue by myounus96** [saadpasta/developerFolio#208]
## Summary
Please add links or sources from where we can get images related to images already in the project
image like this
![image](https://user-images.githubusercontent.com/13608139/87254095-952cc100-c499-11ea-8e64-0f9ec4b7a484.png)
and icon in the title.

**Comment by naveen521kk** [comment]
It's in [Readme.md](https://github.com/saadpasta/developerFolio#illustrations) also btw the one in title is not an icon it is just text with font changed.

**Comment by kartikcho** [comment]
Closing since this seems resolved.
