### ISSUE TITLE
Add Language Switch

### ISSUE THREAD

**Issue by samuk190** [saadpasta/developerFolio#215]
I'm from Brazil and I love the project, it would be nice to have Language Switch Feature where you can just write text in a file and make the user choose which language, If not possible to add in near future, I will work on this feature on the weekends and do a pull request for it ^^

**Comment by naveen521kk** [comment]
AFAIK you can directly change portfolio.js with your language and this will appear on the site in that language. 
If you meant something like changing the language dynamically then it is a good idea. But IMO nobody would have a language switch in their portfolio. What do you think @saadpasta ?

**Comment by samuk190** [comment]
> AFAIK you can directly change portfolio.js with your language and this will appear on the site in that language.
> If you meant something like changing the language dynamically then it is a good idea. But IMO nobody would have a language switch in their portfolio. What do you think @saadpasta ?

Idk where you're from but I'm from brazil and people from HR like to read in portuguese while some others like english, or to be recruited by foreign company

**Comment by naveen521kk** [comment]
If you like to you can make a PR. But do find a good place to place the switch. 😀 
I am assinging you the issue.

**Comment by kartikcho** [comment]
Due to inactivity I'm unassigning this. Also, closing this for now since we don't intend to have localization added, at least for the distant future.
