### ISSUE TITLE
Do a Information Update (portfolio.js)

### ISSUE THREAD

**Issue by raflisboa** [saadpasta/developerFolio#216]
## Summary
I need do an update into portfolio.js file after deploy.

### Additional context
Sorry, but I do a research and didn't find anything like this.

**Comment by naveen521kk** [comment]
Could you explain more on this? 

From what I understood, I think you meant that you need to do update some information on your portfolio after you have deployed?

**Comment by raflisboa** [comment]
Yeah. To be more clear: I did a project deploy, but, now, I need to update an information that is at portfolio.js. 
My point is: which is correct thing that I'm suppose to do?

**Comment by naveen521kk** [comment]
You can simply update `portfolio.js` again, then again deploy by `npm run deploy`. Or manually update by pushing to `gh-pages` branch. And btw that is a easy way to do. And you do that how many times you want.

**Comment by raflisboa** [comment]
Thanks foi your help, but I've been trying this (new deploy) and didn't working. Will I have to commit and push portfolio.js after do a deploy or not?
So, how could I do a mannualy update pushing to gh-pages?

**Comment by naveen521kk** [comment]
> Will I have to commit and push portfolio.js after do a deploy or not?

No, you no need to push `portfolio.js` to your deploy branch.

> So, how could I do a mannualy update pushing to gh-pages?
You should use `npm build` after editing which will create a directory called `build` and you would have to push the content in the `build` directory to `gh-pages` and not other things. I you like to take a visit do see how our `gh-pages` branch is [here](https://github.com/saadpasta/developerFolio/tree/gh-pages).

**Comment by raflisboa** [comment]
When I trying npm run deply command, this error message returns

fatal: destination path 'node_modules\gh-pages\.cache\github.com!raflisboa!developerFolio.git' already exists and is not an empty directory.

What's does mean? Should I delete this folder?

Sorry but I'm a newbee into React dev, and thanks for your help!

**Comment by naveen521kk** [comment]
Did you do `npm install` before doing it? If yes, then does `npm run build` command works? Or, `npm start`?

**Comment by raflisboa** [comment]
> Did you do npm install before doing it?
Yes, and it goes well, without failures.
>  If yes, then does npm run build command works?
Yes, and it goes well, too, without failures.

> Or, npm start?
Yes, and it goes well, too, without failures (localhost show webpage with new implementations

But, now, when I do a `npm run deploy `, npm returns with this:

`Filename too long`
`fatal: Could not reset index file to revision 'origin/master'.`

**Comment by naveen521kk** [comment]
A basic question did you clone this repository or your fork?
You should actually clone your fork. You could check whether any the following listed [here](https://create-react-app.dev/docs/deployment/#troubleshooting) happens for you. Also, try out afresh if this fails. :)

**Comment by raflisboa** [comment]
Ok, I´ll try clone my fork. Thanks!
