### ISSUE TITLE
Issue: Saad Pasta name should not break in medium size viewport.

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#230]
**Issue**: `Saad Pasta` name should not break in medium size viewport.
![image](https://user-images.githubusercontent.com/49693820/89712828-fd939300-d9b0-11ea-8a15-5f6de9ecd3ce.png)

_Originally posted by @naveen521kk in https://github.com/saadpasta/developerFolio/pull/92#issuecomment-670935058_

**Comment by zekinah** [comment]
I just created a PR #233 for this, a small change is applied.

**Comment by saadpasta** [comment]
fix in #233
