### ISSUE TITLE
Add 'Table of Contents' to readme

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#239]
Taking a look at our current README can be daunting to starters due to the size of it. Also, there's no easy way to navigate to a section of the documentation. 

Adding something similar to how most projects with long docs should be a good start.
[Example](https://github.com/axios/axios/blob/master/README.md)

**Comment by anshdhinhgra47** [comment]
I would like to work on this issue. Could you please let me know your requirements.

**Comment by kartikcho** [comment]
Hi @anshdhinhgra47, thanks for offering your help! 

I don't have any specific layout of the content in mind so feel free to change the order of sections as you see fit. The documentation is already pretty uniform, some changes that could benefit from a reorder would be for example, moving project license section to the end of the readme.

**Comment by anshdhinhgra47** [comment]
Alright. I will make the necessary changes required.

**Comment by anshdhinhgra47** [comment]
Seems like you have already accepted a PR. Should I make changes or not ?

**Comment by kartikcho** [comment]
@anshdhinhgra47 #240 only changed position of license section in the readme, you can still add an index to the readme from the example I linked in the description.

Something like this,

![image](https://user-images.githubusercontent.com/48270786/92436880-58442880-f1c3-11ea-9e2a-dcbc53abef21.png)

**Comment by kartikcho** [comment]
Are you still working on this @anshdhinhgra47 ?

**Comment by kartikcho** [comment]
Due to lack of activity, I'm unassigning this.

**Comment by palak-sethi** [comment]
Hi, I'd like to work on this issue

**Comment by naveen521kk** [comment]
Sure. I will assign you @palak-sethi

**Comment by kartikcho** [comment]
lol that was fast, assigning this to you!

**Comment by naveen521kk** [comment]
Fixed in #256
