### ISSUE TITLE
Docker commands result in error

### ISSUE THREAD

**Issue by Tasin5541** [saadpasta/developerFolio#248]
**Describe the bug**
`docker build -t developerfolio:latest .` results in no such file or directory in the `npm install` step. Deleting package-lock.json seems to fix that problem

Running `docker run -p 3000:3000 developerfolio:latest` results in exiting the container immediately after starting. The webpage doesn't show up on http://localhost:3000/

**Expected behavior**
`docker build -t developerfolio:latest .` should build the image.
`docker run -p 3000:3000 developerfolio:latest` should keep running the website locally until exiting manually.

**Is this responsiveness Issue**
NO

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by saadpasta** [comment]
@kartikcho can you look into this. I don't have a docker on my PC right now.

**Comment by kartikcho** [comment]
> I don't have a docker on my PC right now. 

Same 😅, I'll try reproducing it over the weekend.
CC @naveen521kk

**Comment by naveen521kk** [comment]
> I don't have a docker on my PC right now
Same for me also. ( I have never installed it).😂

**Comment by abhishekashyap** [comment]
Can I take this up?

**Comment by saadpasta** [comment]
Sure Go Ahead ☺️

**Comment by kartikcho** [comment]
Great! Were you able to repro it successfully @abhishekashyap ?

**Comment by abhishekashyap** [comment]
yes
