### ISSUE TITLE
Add Lottie illustrations behind a preference

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#257]
The current illustrations, although look good with the current aesthetic, are static and don't sit right with the recent 'interactive' animations added. 
We can add a switch to use [Lottie illustrations](https://github.com/airbnb/lottie-web) instead of the current ones based on what the user decides in `portfolio.js`.
This does have a downfall, Lottie is pretty performant but still might have performance issues running on slower systems. Hence, the switch to use it or not.

cc: @saadpasta @naveen521kk

**Comment by saadpasta** [comment]
@kartikcho Look's great can you add a gif or provide a video or something that would be great. ✌️ 
And I guess we should also keep simple illustration if someone needs them and add a key for that in portfolio.js``

**Comment by naveen521kk** [comment]
Look great!
A gif or a test deployment would help a lot.

PS. Just a thing which hurt me on first look is the small letter `i` in `What I do`.
