### ISSUE TITLE
Add options to set color theme globally

### ISSUE THREAD

**Issue by fabianchua6** [saadpasta/developerFolio#262]
## Summary
Would be cool if we were able to change the accent or the colour of the theme somewhere!

### Motivation
That way it makes it more customisable and maybe unique for each individual.

**Comment by kartikcho** [comment]
This was something on my mind too but would require a bit of rework. I'll add it to the list though. Thanks!

**Comment by kartikcho** [comment]
Closing this as it is a duplicate of #322 (although this is the original) 
This is still definitely on the list!
