### ISSUE TITLE
Dark mode slider looking weird

### ISSUE THREAD

**Issue by fabianchua6** [saadpasta/developerFolio#263]
**Describe the bug**
Dark mode slider is fine when it's in dark mode but when toggled to light mode, the toggle leaves a weird gap in the slider itself.

**To Reproduce**
1. Click on dark mode toggle to light mode.
2. See error where there is a gap between the toggle and the slider

**Screenshots**
![image](https://user-images.githubusercontent.com/57614749/96021085-8a5f3f00-0e81-11eb-94b8-db999b44d7a8.png)
As you can see, there is abit of blue on the right of the toggle.

**Comment by kartikcho** [comment]
Ah, I noticed this too but it might've slipped through. Would you like to open a PR for this @fabianchua6 ?

**Comment by WarenGonzaga** [comment]
@kartikcho can I take this issue?

**Comment by fabianchua6** [comment]
Sure please!

**Comment by kartikcho** [comment]
@fabianchua6 just confirming if you wanted to take the issue or are okay with someone else making a PR for it?

**Comment by WarenGonzaga** [comment]
I'm working on it @kartikcho @fabianchua6

**Comment by fabianchua6** [comment]
> @fabianchua6 just confirming if you wanted to take the issue or are okay with someone else making a PR for it?

I’m fine with it! Thanks for asking 👍🏻

**Comment by WarenGonzaga** [comment]
Hi @saadpasta done with this issue kindly review it I add additional update which is Vulnerability fixes on your npm packages.

**Comment by WarenGonzaga** [comment]
@saadpasta I guess this is done? you can close now.

**Comment by saadpasta** [comment]
@WarenGonzaga We can close the issue only after the PR is merged.

**Comment by kartikcho** [comment]
fixed in #264
