### ISSUE TITLE
Redesign 'Big Projects' section

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#280]
The `Big Projects` section feels out of context as of current portfolio standards and I believe could use an overhaul.

Maybe we could build this into a `Case Studies` section for projects with more information about the user's work on it or implementation. 

We could,

 - add a 'Read more' button that would open a big modal with a placeholder page (user can change it accordingly) 
 - or add dynamic routing to a new page but that would no longer leave the portfolio a SPA.

Open to discussions & mocks before we move on to implementation.

**Comment by 1hanzla100** [comment]
I want to redesign big projects section

**Comment by kartikcho** [comment]
Sure, that sounds great. Could you come up with a mock for a design you might have in mind? 
That way the team can decide upon it and you can have a finalized design to start writing code for.

**Comment by 1hanzla100** [comment]
### Something Like That

On Hover Effect Card Shadow Increases

![Capture](https://user-images.githubusercontent.com/59178380/104883151-22d7f480-5986-11eb-84ec-0de265e6ae95.PNG)

**Comment by kartikcho** [comment]
Although the design looks nice, introducing a completely new dependency, i.e Bootstrap, isn't worth it just for a card component. 
If you can write the CSS for a simple card, I believe that would be best.

Also, you should allow the user to add an image inside the card yet still keep it flexible enough to look great when an image isn't provided.

Something like this for reference,
![image](https://user-images.githubusercontent.com/48270786/104891867-7bfc5400-5997-11eb-872d-d2217be591fb.png)

**Comment by 1hanzla100** [comment]
Sure i can use css for redesign big projects section. Design would be quite similar to achievements section.
Layout will be 2 in row in large screen
1 in row in small screen

**Comment by kartikcho** [comment]
I think 2 or 3 in a row for larger screens would be great, no strong preference as long as its responsive. 
Everything sounds good, you can start working on it unless you need some more information.

**Comment by kartikcho** [comment]
Taking inspo from your proposed design, the card can have space in the left of the card below to have a square image.

![image](https://user-images.githubusercontent.com/48270786/105060433-6a51a400-5a9e-11eb-94e0-a58acf1fe363.png)

This could be flexible to revert to the upper design if no image is provided.

**Comment by 1hanzla100** [comment]
ok i am going to  to work on it.

**Comment by 1hanzla100** [comment]
@saadpasta @kartikcho  Successfully Redesigned Big Projects Section. Kindly Review the Pull Request

**Comment by kartikcho** [comment]
Hey @1hanzla100 you can also use the 'Request review' button on your PR to save you the trouble of pinging people in issues for a review in the future!

**Comment by 1hanzla100** [comment]
> Hey @1hanzla100 you can also use the 'Request review' button on your PR to save you the trouble of pinging people in issues for a review in the future!

@kartikcho ok

**Comment by kartikcho** [comment]
Addressed in #305
