### ISSUE TITLE
How can I set the website default in dark mode?

### ISSUE THREAD

**Issue by jatindhar** [saadpasta/developerFolio#287]
While opening the site, it should be default in dark mode and with toggle switch we can change it to light mode.

**Comment by WarenGonzaga** [comment]
Is this kind of default mode to setup?

**Comment by saadpasta** [comment]
The website would open in the dark mode as default if your mac/windows theme is dark.

**Comment by kartikcho** [comment]
Can we setup GitHub Discussions to handle these usage issues? I've never tried it and it seems more appropriate to handle these responses.

**Comment by saadpasta** [comment]
@kartikcho I don't think we need open Github Discussions for this issue.

**Comment by kartikcho** [comment]
Not for this issue, for further queries maybe. But it's just a suggestion, no strong feelings.

**Comment by saadpasta** [comment]
@kartikcho No problem mate. But good suggestion. 👍
