### ISSUE TITLE
ContactInfo Section is not loading the title,number or email address correctly

### ISSUE THREAD

**Issue by rasam-hossain** [saadpasta/developerFolio#294]
**Issue**: ContactInfo title/phone number/email is not showing up the correct data. 

**Details**:
'contactInfo' section keeps showing "Reach out to me" and no data about phone number or email address. I can change the subtitle to anything else and it works just fine but not the title, phone number, email address, or lottie.
![image](https://user-images.githubusercontent.com/10996219/103466152-4eb17400-4d10-11eb-9f06-6a687d66ffe8.png)

Here's the code I have from my portfolio.js
![image](https://user-images.githubusercontent.com/10996219/103466164-802a3f80-4d10-11eb-9174-5ebbde9a620b.png)

**Note**:
"Contact Me ☎️" and the appropriate Lottie/animation was showing up correctly but the Github portfolio was not showing up at all and no matter what I do using just the env file for adding my Github token didn't work and keep constantly showing FailedToLoad in the console. So, I was finally able to solve this issue by using the technique of 
`$env:REACT_APP_GITHUB_TOKEN = "my_unique_token"` in Powershell. Now the Github profile is showing up but not the contactInfo section. Any idea what's breaking this and where is this _"Reach out to me"_ coming from?
A production build can be found here with this issue: [https://rasam-hossain.github.io/](https://rasam-hossain.github.io/)

**Comment by rasam-hossain** [comment]
Just a note on the issue [#293](https://github.com/saadpasta/developerFolio/pull/293) - Changing the emailAddress field doesn't solve the issue with contactInfo

**Comment by saadpasta** [comment]
@rasam-hossain it's because you don't have an email in your GitHub profile add an email in your GitHub profile and then check again

**Comment by saadpasta** [comment]
@rasam-hossain if you want to get your contact info from portfolio.js then set `showGithubProfile `to "false"

```
const openSource = {
  githubConvertedToken: process.env.REACT_APP_GITHUB_TOKEN,
  githubUserName: "saadpasta", // Change to your github username to view your profile in Contact Section.
  showGithubProfile : "false",  // Set true or false to show Contact profile using Github, defaults to true
  display: true // Set false to hide this section, defaults to true
};
```

**Comment by rasam-hossain** [comment]
@saadpasta - I see. The _contact info_ is working now. Thanks a lot!

**Comment by saadpasta** [comment]
@rasam-hossain Welcome. Thanks for using DeveloperFolio ❤️
