### ISSUE TITLE
Emoji Render Issue 

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#3]
Emoji do not render on every platform and browser

**Comment by naveen521kk** [comment]
We can use this https://github.com/twitter/twemoji if emoji render problem occurs.

**Comment by naveen521kk** [comment]
The wave emoji is not showing. Check the picture attached.
https://i.ibb.co/0JcvRGP/2020-03-19-15-14-36.jpg

**Comment by kartik918** [comment]
Where did you reproduce this bug @naveen521kk . Would appreciate more information to find a solution for this.

**Comment by naveen521kk** [comment]
@kartik918 I found this bug in Google Chrome in my phone Samsung J7. Would appreciate if fixed.

**Comment by kartik918** [comment]
I'm thinking of using twitter emojis too because that will give flexibility of using other emojis to the user and not worrying about compatibility. Do you want to help out with this?

**Comment by naveen521kk** [comment]
I would soon make a pull request on that.
