### ISSUE TITLE
How to remove some section from the site?

### ISSUE THREAD

**Issue by jatindhar** [saadpasta/developerFolio#309]
I want to remove bigProjects, Talks & Podcast section, how to do that?

**Comment by saadpasta** [comment]
There is a Key **`display`** for every section in `portfolio.js` set that to false to hide that section.

Thanks ✌️

**Comment by jatindhar** [comment]
> There is a Key **`display`** for every section in `portfolio.js` set that to false to hide that section.
> 
> Thanks

Sorry to bother you again but I'm not getting any **display** keyword in **portfolio.js** or in there particular js code? Can you tell me exactly where to change the code? 

And thanks in advance :+1:

**Comment by 1hanzla100** [comment]
@jatindhar In ```containers\Main.js```
Comment Those Components out which you want to exclude like this.
![Capture](https://user-images.githubusercontent.com/59178380/106348820-f22f7d80-62ea-11eb-9e67-4b8fe2273091.PNG)

**Comment by jatindhar** [comment]
> @jatindhar In `containers\Main.js`
> Comment Those Components out which you want to exclude like this.
> ![Capture](https://user-images.githubusercontent.com/59178380/106348820-f22f7d80-62ea-11eb-9e67-4b8fe2273091.PNG)

Thank you soo much!! :+1:
