### ISSUE TITLE
[Design] Merge Blogs section and Talks section into one

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#31]
The current design for the above mentioned feel bland and out of place at the moment. Maybe merge them into one component or add a carousel slider to switch between the two maybe?
This could help fill Blogs section up and make it look more consistent with the design.

### Also this needs a thumbnail lol
![Screenshot (66)](https://user-images.githubusercontent.com/48270786/71304770-e2a7ea80-23f0-11ea-8287-923498bfeacd.png)

**Comment by saadpasta** [comment]
@kartik918 Yes I agree with but merging them into one is not a good idea I guess we should create a new card for Talk Section what do you think

**Comment by kartik918** [comment]
Maybe use a different layout for talks, something similar to the new podcast section design.
Smaller in layout and thumbnail less if possible because talks don't really need a thumbnail unless you want to put a picture from the event. I'll see if I find some design inspiration or ideas, you can help too

**Comment by saadpasta** [comment]
@kartik918 Thanks. I'll also have a look for design and upload it here so we both can see if it look good or not

**Comment by kartik918** [comment]
Okay I found one design inspo worth changing to if you want to insert pictures with

![Screenshot (74)](https://user-images.githubusercontent.com/48270786/71372869-805f0d80-25db-11ea-9b50-e6abcc3c7402.png)

Or my own design (don't judge my mad designing skills, I used paint for a quick mockup) for text only design

![Screenshot](https://user-images.githubusercontent.com/48270786/71372936-a71d4400-25db-11ea-8185-b40181d0e6e0.png)

**Comment by saadpasta** [comment]
@kartik918 Love both designs. But where should we implement this design should we change blogs or Talk Section

**Comment by kartik918** [comment]
Talk section needs the rework so I guess we change talks card design.

**Comment by saadpasta** [comment]
@kartik918 OK Let's change the talk section

**Comment by kartik918** [comment]
Are you designing it? Maybe put a PR and I'll give second opinion on the layout? @saadpasta

**Comment by saadpasta** [comment]
@kartik918 No, I am stuck with something else I would be very thankful if you could make a PR.

**Comment by kartik918** [comment]
I'll make one if I find the time.

**Comment by saadpasta** [comment]
fixed in #32
