### ISSUE TITLE
Github personal access token is always expiring :(

### ISSUE THREAD

**Issue by darkhorse-coder** [saadpasta/developerFolio#310]
Hi @saadpasta 
Thank you for your great project. I really love this portfolio template.

How can I avoid expiring of github personal access token when publish to vercel?
Already I've created really basic token without any selection of scope. but when I deploy to vercel, token has removed.

Thank you in advance.

**Comment by tamojit-123** [comment]
@darkhorse-coder You need to check all the boxes for GitHub access token to get full-time access. vercel Issue will get resolve. Check all the boxes while generating the token.

**Comment by darkhorse-coder** [comment]
@tamojit-123 I've tried with lots of case, also I've tried with https://d.pr/v/cQXAGD, but not working.

**Comment by darkhorse-coder** [comment]
Hi @saadpasta @tamojit-123 
any news? please help me.

**Comment by saadpasta** [comment]
Are you putting the token in environment file.
.env

**Comment by darkhorse-coder** [comment]
yes, write on .env file to REACT_APP_GITHUB_TOKEN

**Comment by darkhorse-coder** [comment]
I've created token as simple without any selection of scope.

**Comment by naveen521kk** [comment]
Have a look at the new documentation, and see if it is fixed there. https://github.com/saadpasta/developerFolio/pull/343
