### ISSUE TITLE
It's showing error while running npm run deploy

### ISSUE THREAD

**Issue by jatindhar** [saadpasta/developerFolio#317]
![error](https://user-images.githubusercontent.com/56015460/106862811-a36c5400-66ed-11eb-9af6-6b5341462461.JPG)

**Comment by saadpasta** [comment]
Please change your remote origin URL to your personal repo. Hope this helps. 
https://docs.github.com/en/github/using-git/changing-a-remotes-url

**Comment by jatindhar** [comment]
Thankx alot :+1:
