### ISSUE TITLE
How to edit the website after hosting?

### ISSUE THREAD

**Issue by jatindhar** [saadpasta/developerFolio#319]
I've hosted the website through react application on GitHub pages but now I want to remove some section but now repo have totally different source codes! How to make change in the website now?

**Comment by saadpasta** [comment]
@jatindhar I see you have deployed your website on the main GitHub page and your build folder is now on your master branch. You need to create a branch and deploy from there. 
have a look at [https://github.com/saadpasta/saadpasta.github.io/ ](https://github.com/saadpasta/saadpasta.github.io/ ) branch structure

**Comment by jatindhar** [comment]
Got it, Thanks a lot :+1:
