### ISSUE TITLE
Add different variations of similar components

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#321]
I've received a lot of feedback regarding portfolios generated from our app looking too similar. To tackle this problem for users, I think we can build different 'versions' of a component to provide even more flexibility in design and how data is displayed.

This is a broader issue that would require some time to work so we can use a checklist to track different component versions.

- [ ] Landing
- [ ] Github Projects
- [ ] Skills Section
- [ ] Experience cards
- [ ] Blog Cards

_Feel free to add more ideas or components that could use a different variation_

**Comment by saadpasta** [comment]
@kartikcho good one. I think the first thing we can work on is that make the color scheme dynamic.

**Comment by kartikcho** [comment]
Definitely +1 on that, we can probably handle that through CSS global variable config.

I was planning to cover it under a different issue since that is more about refactoring.

**Comment by saadpasta** [comment]
> Definitely +1 on that, we can probably handle that through CSS global variable config.
> 
> I was planning to cover it under a different issue since that is more about refactoring.

Sure let's make another issue for that.

**Comment by saadpasta** [comment]
@kartikcho I'll create that.

**Comment by JaiminR28** [comment]
Is the issue still active ? I can work on it.

**Comment by saadpasta** [comment]
Nope closing it
