### ISSUE TITLE
Dynamic Color Scheme 

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#322]
## Summary
Currently, we are only one single color scheme in DeveloperFolio. We need to make it dynamic. 

### What's new?
We need to create a global CSS variable or something like that portfolio,js so we can get the same color across all components 

### Motivation
So a user could change the color scheme to their own preference

**Comment by kartikcho** [comment]
Assigning this to @SJellen

**Comment by kartikcho** [comment]
This has been delivered in #355
