### ISSUE TITLE
Security Vulnerabilities - 5 vulnerabilities (1 low, 4 high) - npm audit

### ISSUE THREAD

**Issue by jayhawk24** [saadpasta/developerFolio#323]
**Describe the bug**

**To Reproduce**
1. run `npm i`
2. `npm audit`

**Expected behavior**
No vulnerabilities detected after running npm install.

**Is this responsiveness Issue**
No

**Screenshots**
`
❯ npm i

added 1696 packages, and audited 1697 packages in 2m

5 vulnerabilities (1 low, 4 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
❯ npm audit
### npm audit report

ini  <1.3.6
Prototype Pollution - https://npmjs.com/advisories/1589
fix available via `npm audit fix`
node_modules/ini

object-path  < 0.11.5
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1573
fix available via `npm audit fix`
node_modules/object-path
  adjust-sourcemap-loader  0.1.0 - 2.0.0
  Depends on vulnerable versions of object-path
  node_modules/adjust-sourcemap-loader
    resolve-url-loader  0.0.1-experiment-postcss || 2.0.0 - 3.1.1 || >=4.0.0-alpha.1
    Depends on vulnerable versions of adjust-sourcemap-loader
    node_modules/resolve-url-loader
      react-scripts  3.1.0 - 3.4.3 || 4.0.0-next.64 - 4.0.0-next.117
      Depends on vulnerable versions of resolve-url-loader
      node_modules/react-scripts

5 vulnerabilities (1 low, 4 high)

To address all issues, run:
  npm audit fix

`

**Comment by kartikcho** [comment]
Hi, thanks for reporting this. I'll open a PR soon fixing this after some crucial PRs are in. Thinking of doing a bunch of code cleanup PRs.

**Comment by kartikcho** [comment]
Fixed in #326
