### ISSUE TITLE
I was trying to build the docker image based on the existed Dockerfile until this happened !!

### ISSUE THREAD

**Issue by ismailalabou** [saadpasta/developerFolio#327]
**Describe the bug**
the bug is related to Docker Commands section (first command):
1) BUILD IMAGE : ```docker build -t developerfolio:latest .```

**To Reproduce**
1. cd to the project root folder
2. run : ```code .```
3. in the terminal run : ```docker build -t developerfolio:latest .```
4. See error: ```ERROR [4/6] RUN npm install```

**Expected behavior**
build docker image from Dockerfile successfully.

**Is this responsiveness Issue**
NO

**Screenshots**
https://imgur.com/a/c4SrfdT

**Desktop:**
 - OS: windows 10
 - Browser: google chrome
 - Version: 88

**Additional context**
> COMMAND that triggered this error :
```docker build -t developerfolio:latest .```

**Comment by ismailalabou** [comment]
FROM node:12.18.1-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production
RUN npm audit fix

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

**Comment by ismailalabou** [comment]
i even 

> ```
> FROM node:12.18.1-alpine
> ENV NODE_ENV=production
> 
> WORKDIR /app
> 
> COPY ["package.json", "package-lock.json*", "./"]
> 
> RUN npm install --production
> RUN npm audit fix
> 
> COPY . .
> 
> EXPOSE 3000
> 
> CMD ["npm", "start"]
> ```

i even tried this dockerfile version, but without any luck

**Comment by naveen521kk** [comment]
WSL is used, so I think `npm start` won't work...
never tried it but I can help if you paste the logs instead of taking a screenshot.

**Comment by ismailalabou** [comment]
@naveen521kk what makes you think WSL was used...

**Comment by ismailalabou** [comment]
> WSL is used, so I think `npm start` won't work...
> never tried it but I can help if you paste the logs instead of taking a screenshot.

the logs files are inside my image, which was never been build.
so i can't access them xD

**Comment by naveen521kk** [comment]
> @naveen521kk what makes you think WSL was used...

because there isn't any windows target in https://hub.docker.com/_/node and I was reading https://docs.microsoft.com/en-us/windows/nodejs/containers

**Comment by naveen521kk** [comment]
> the logs files are inside my image, which was never been built.
so i can't access them xD

I was asking for the logs which were printed on the screen,

**Comment by ismailalabou** [comment]
i will send theme to you once i got theme again.
thanks

**Comment by naveen521kk** [comment]
wdymb `theme`?

**Comment by ismailalabou** [comment]
i mean them not "theme" mb

**Comment by naveen521kk** [comment]
@ismailalabou any updates?

**Comment by ismailalabou** [comment]
I'm experiencing some issues/problems with my docker, that's why i didn't leave any feedback/updates on this issue.

**Comment by ismailalabou** [comment]
> in that case, I'm closing this issue.

feels bad man

**Comment by naveen521kk** [comment]
for me, it works here. So, I would simply say "can't reproduce". :)

**Comment by ismailalabou** [comment]
> for me, it works here. So, I would simply say "can't reproduce". :)

I think your environment either macOS or Linux.

**Comment by ismailalabou** [comment]
Building the docker image FINISHED successfully.
