### ISSUE TITLE
Projects not shown when using on mobile

### ISSUE THREAD

**Issue by JavaidAhmadKhan** [saadpasta/developerFolio#339]
Hey, this is one of the best portfolios which I have seen till now, thanks for your valuable time. I m not able to see the prjoects screen on my mobile, is this an issue.

**Comment by naveen521kk** [comment]
Could you try it now? A few hours back there was a problem with deployment so it didn't show on both mobile and also PC.

**Comment by kartikcho** [comment]
Can you confirm @JavaidAhmadKhan? If it's okay now, you can close the issue.

**Comment by naveen521kk** [comment]
Closing the issue because of no response.
