### ISSUE TITLE
Images src gets set to [object Module]

### ISSUE THREAD

**Issue by Lemorz56** [saadpasta/developerFolio#340]
**Describe the bug**
Image src in for example educationInfo gets set to 
`<img crossorigin="anonymous" class="experience-roundedimg" src="[object Module]" alt="Hitachi ABB">`

My guess looking online is something to do with file-loader.

**To Reproduce**
1. Update npm modules (otherwise npm start will not run)
2. Start the app
3. Scroll down to image
4. Image not loaded

**Expected behavior**
The image should be displayed and the img tag should be set correctly.

**Is this responsiveness Issue**
NO

**Screenshots**
Heres a picture of the image not showing up:
![image](https://user-images.githubusercontent.com/1346676/110376955-1c93f980-8054-11eb-82c5-8f8e4569f94d.png)

And heres a picture of the code from the inspector:
![image](https://user-images.githubusercontent.com/1346676/110377035-32a1ba00-8054-11eb-89be-70647b5a1f59.png)

Heres the line of code for the picture itself:
`companylogo: require("./assets/images/hitachiABBlogo.png"),`

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 88.0.4324.190

**Comment by naveen521kk** [comment]
Can you show me what have you changed? Because I don't see that happen in https://developerfolio.js.org/#education

> Update npm modules (otherwise npm start will not run)

Can you explain why it doesn't? It works here.

>  companylogo: require("./assets/images/hitachiABBlogo.png"),

Does the image exists in `src/assets/images/hitachiABBlogo.png`?

I would appreciate if you give can a web deploy where it happens say on Vercel or Pages.

**Comment by byteyoo** [comment]
Hello @Lemorz56 and @naveen521kk,

I was able to fix this problem by accessing the string value through the 'default' property:
`require('./assets/images/logo-1.png').default`

Have a great day!

**Comment by Lemorz56** [comment]
> Hello @Lemorz56 and @naveen521kk,
> 
> I was able to fix this problem by accessing the string value through the 'default' property:
> `require('./assets/images/logo-1.png').default`
> 
> Have a great day!

Thanks alot, it worked. Guess something changed in the file-loader updates?
