### ISSUE TITLE
Document about change in loading Profile

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#342]
Document things changed from https://github.com/saadpasta/developerFolio/pull/333

**Comment by kartikcho** [comment]
If we're looking for external contributors to help improve documentation for this, I think they'll need a bit more context to work with it @naveen521kk. 
Also, add labels too so contributors can figure out difficulty or status of the task.

**Comment by naveen521kk** [comment]
It was an issue for me to do it. :)
essentially I still get to it, but soon will.
