### ISSUE TITLE
After 'npm start' command line, About the Github Username problem.

### ISSUE THREAD

**Issue by young-hun-jo** [saadpasta/developerFolio#344]
**Describe the bug**
I want to use your awesome developerFolio project. but I encountered the problem. I was doing your tutorial on readme.md and I finish your npm install. but when I enter 'npm start' command line, I got a error message "throw "Github Username was found to be undefined. Please set an Environment variable." Why the error is occurred? I am novice in Node.js.. So I really need your help. Thanks.

**Screenshots**
<img width="676" alt="스크린샷 2021-03-26 오후 5 02 38" src="https://user-images.githubusercontent.com/54783194/112600878-145dfb80-8e55-11eb-9f13-ce1ff482fa80.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version:89

**Comment by naveen521kk** [comment]
It is in the process of documentation https://github.com/saadpasta/developerFolio/pull/343
