### ISSUE TITLE
React scripts module Problem.

### ISSUE THREAD

**Issue by young-hun-jo** [saadpasta/developerFolio#345]
**Describe the bug**
I almost have done clone... but I encountered module problem. I definitely installed Node.js and npm but this problem is occurred. How I solve this problem? Thanks!

<img width="676" alt="스크린샷 2021-03-26 오후 6 09 41" src="https://user-images.githubusercontent.com/54783194/112609079-70794d80-8e5e-11eb-87a7-e7d691b1a4f3.png">

**Comment by naveen521kk** [comment]
did you run `npm install` first?

**Comment by young-hun-jo** [comment]
Yes. I already installed it.

<img width="676" alt="스크린샷 2021-03-26 오후 7 18 06" src="https://user-images.githubusercontent.com/54783194/112617193-fea60180-8e67-11eb-8142-42d71a9aa386.png">

**Comment by young-hun-jo** [comment]
the result of ``npm start`` is equal to the former(``npm run deploy``). Should I remove the existing npm, Node.js and reinstall them?

**Comment by young-hun-jo** [comment]
I resolved this problem to refer #139 !
