### ISSUE TITLE
"npm run deploy" command Error : [403] Request Error

### ISSUE THREAD

**Issue by young-hun-jo** [saadpasta/developerFolio#346]
**Describe the bug**
1. After finishing ``npm start``, I could get my own github pages(DNS is localhost:0000) cloning your awesome portfolio template.  But when I command ``npm run deploy``, I encountered final problem.. 

<img width="702" alt="스크린샷 2021-03-26 오후 9 10 21" src="https://user-images.githubusercontent.com/54783194/112629434-ad9e0980-8e77-11eb-8a25-3d674e1a0e5e.png">

2. And I have another question. I wonder if the fact that I know is correct. I am doing ``npm start`` or ``npm run deploy`` command in your project(I was cloning before). Is this right? After I make my own repository for github.io and I cloned your repository in my own repo, if I enter ``npm start`` or ``npm run deploy``  I encountered ``MODULE_NOT_FOUND`` error. (p.s I definitely installed ``npm``, ``node.js``) Should I have to run ``npm start`` in only your project?

**Comment by sadapasta** [comment]
@young-hun-jo you need to change the remote to your repo. Hope this help

https://docs.github.com/en/github/getting-started-with-github/managing-remote-repositories

**Comment by young-hun-jo** [comment]
Oh I resolve my problem by myself! Thank you for your comment. I can use your awesome template. Definitely I always refer your copyright. Thanks again!

**Comment by naveen521kk** [comment]
Hope it's fixed. Closing.
