### ISSUE TITLE
GA(Google Analytics) can be applied to this template?

### ISSUE THREAD

**Issue by young-hun-jo** [saadpasta/developerFolio#350]
Hi. I have using your template well! I have a question about yours. 

I want to use GA(Goole Analytics) analysis in my github pages(applied to your template) and want to analyze how many people visit my page. 
Is there a way to use GA in my page? 

Thank you!

**Comment by naveen521kk** [comment]
You can edit 
https://github.com/saadpasta/developerFolio/blob/04bfd7df470209ff6935271ce57b418db16e022c/public/index.html#L28-L36
accordingly and GA should work.

**Comment by young-hun-jo** [comment]
Thanks!
