### ISSUE TITLE
How can I add custom icons

### ISSUE THREAD

**Issue by pgyogesh** [saadpasta/developerFolio#351]
## Summary
Need to add custom icon in skills sections

### What's new?
There are few icon not available for font-awesome for example icon for PostgreSQL

### Motivation
By doing this, I'll be able to add png icons and not limited to font-awesome

**Comment by kartikcho** [comment]
You could use your own icons by tweaking with the current implementation of the icons to use custom icons.

**Comment by ashwink-tech** [comment]
In which file is this implementation present?

**Comment by kartikcho** [comment]
[This](https://github.com/saadpasta/developerFolio/blob/master/src/portfolio.js#L56) is where the icons are being defined and they're being rendered [here](https://github.com/saadpasta/developerFolio/blob/master/src/components/softwareSkills/SoftwareSkill.js).

**Comment by ashwink-tech** [comment]
Thanks @kartikcho
