### ISSUE TITLE
More Documentation for ease of user/programmer

### ISSUE THREAD

**Issue by willwalsh96** [saadpasta/developerFolio#353]
## Summary
I think this project would benefit from more documentation to teach the user what each line of code does. Maybe not every single line, but certainly more could be done. I understand this is a free project made with some intent of helping people build websites. Possible because they don't have the skills yet to do so alone?
Would you guys post what sections you want explained or commented on? I'll try to do some reverse-engineering and issue diving to make it more palatable.

### Motivation
I spent a couple hours and about 40 build attempts trying to remove the Podcast section before my noob-brain decided to check the issues doc. I'm a very important man and my time is very valuable :p. No but it seems easy enough to me to add a line saying "//sections can be turned off by setting value to false, or by commenting out this line here in this manner."
Moreover, if I use this site as my own portfolio, people I interview with are going to ask me what I know about it or React, y'know? and the answer could be honestly telling them its a public GitHub project that I worked on and that I actually don't know how it works.

**Comment by kartikcho** [comment]
Hey @willwalsh96, I understand your point and it would make sense to create an explanation doc if it were built as a sort of teaching project. 
While the React patterns and code used isn't that complex, it can still be overwhelming to programmers new to React. However, I don't think we plan to create docs explaining components and the structure anytime soon as maintenance and adding new features can already take up most of the time the collaborators spend on this project.

There was this youtube course that used this project in one of their React videos which might be helpful to you I hope. 
@saadpasta could you link to it as it was an unlisted video if I remember correctly.

Closing this as it isn't on the list of stuff we plan to add and thanks for the reminder that we should update the docs to be even more beginner friendly!

**Comment by sadapasta** [comment]
@willwalsh96 Hope this helps 

https://www.youtube.com/watch?v=86F11Y56wmI&fbclid=IwAR1aL6zUQuW57G-I0FFwWKD2HAx09M2IvwuhyrR71MazUVqOd315i6u6JSU
