### ISSUE TITLE
npm ERR! git dep preparation failed

### ISSUE THREAD

**Issue by zizopixels** [saadpasta/developerFolio#356]
After running npm install I'm getting this error :

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command D:\nodejs\node.exe C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\zizo-pixels\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\zizo-pixels\AppData\Local\npm-cache\_cacache\tmp\git-clone-9e6a0785\node_modules\iltorb
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./scripts/install.js || node-gyp rebuild
npm ERR! npm ERR! info install installing standalone, skipping download.
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@7.1.2
npm ERR! npm ERR! gyp info using node@15.14.0 | win32 | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.8.9 found at "D:\Python\python.exe"
npm ERR! npm ERR! gyp ERR! find VS
npm ERR! npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! npm ERR! gyp ERR! find VS - not found
npm ERR! npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! npm ERR! gyp ERR! find VS
npm ERR! npm ERR! gyp ERR! find VS **************************************************************
npm ERR! npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! npm ERR! gyp ERR! find VS **************************************************************
npm ERR! npm ERR! gyp ERR! find VS
npm ERR! npm ERR! gyp ERR! configure error
npm ERR! npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\zizo-pixels\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.14393
npm ERR! npm ERR! gyp ERR! command "D:\\nodejs\\node.exe" "C:\\Users\\zizo-pixels\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd C:\Users\zizo-pixels\AppData\Local\npm-cache\_cacache\tmp\git-clone-9e6a0785\node_modules\iltorb
npm ERR! npm ERR! gyp ERR! node -v v15.14.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! npm ERR! gyp ERR! not ok
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\zizo-pixels\AppData\Local\npm-cache\_logs\2021-04-21T04_17_43_762Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zizo-pixels\AppData\Local\npm-cache\_logs\2021-04-21T04_18_14_497Z-debug.log

**Comment by VedanthB** [comment]
Hey, i get this error too

**Comment by kartikcho** [comment]
This seems like a user ended issue and not specific to the project. You could try looking it up for solutions and also provide steps to reproduce the issue if it's still not fixed.

**Comment by Anshluthra1** [comment]
hello kartik bhaiya. while hosting the devloperFolio , im getting a issue pls help
![Screenshot 2021-04-23 at 4 09 17 PM](https://user-images.githubusercontent.com/76260663/115860387-09e05300-a44f-11eb-9e57-d4b32f42647e.png). pls help asap

**Comment by kartikcho** [comment]
You probably haven't added your username in the project environment variables @Anshluthra1. Check [this section](https://github.com/saadpasta/developerFolio#linking-portfolio-to-github) out of the readme for more instructions.

**Comment by Anshluthra1** [comment]
Done bhaiya already

**Comment by Anshluthra1** [comment]
![image](https://user-images.githubusercontent.com/76260663/115880797-bd097600-a468-11eb-9a80-b0163e3bc414.jpeg)![image](https://user-images.githubusercontent.com/76260663/115880798-bd097600-a468-11eb-9213-741cd9b78899.jpeg)

**Comment by kartikcho** [comment]
You should not push your access token to public or private repositories. Since you're using Netlify for deployment, they have their own build time env variable.

Check this https://docs.netlify.com/configure-builds/environment-variables/

**Comment by naveen521kk** [comment]
@Anshluthra1 I have deleted your previous post because it leaks your secrets.

**Comment by Anshluthra1** [comment]
Okay thanks a lot , so kind but pls help me with this
