### ISSUE TITLE
Add a Preloader Screen

### ISSUE THREAD

**Issue by pritishbarabde** [saadpasta/developerFolio#357]
Add a pre loader screen which looks super cool like this one
Link: https://ashutoshhathidara.com/

**Comment by kartikcho** [comment]
Cool idea, do you have any design in mind? We can add something minimalistic from [Spinkit](https://tobiasahlin.com/spinkit/).

Or my own [spinner](https://github.com/tobiasahlin/SpinKit/pull/149) that @tobiasahlin never approved :(

**Comment by pritishbarabde** [comment]
I did select this one but was unable to implement it successfully.
Link: https://lottiefiles.com/58266-quad-cube-shifter-1

**Comment by kartikcho** [comment]
Looks neat! 
We already have a `LottiePlayer` component (although I think we'll have to extend it for this), all you need to do is plug the JSON for this into it.

Are you working on this? So I can assign this to you

**Comment by pritishbarabde** [comment]
Sorry I am a newbie, I just wanted to suggest an improvement.

**Comment by kartikcho** [comment]
Ah, no problem! 
Thanks for the suggestion.

**Comment by pritishbarabde** [comment]
I hope the feature will be added soon!!

**Comment by SJellen** [comment]
The example link loads on page # the after the animation the homepage loads as /#/home
Thats not really possible without changing the website location. Instead it would have to be a component that loads as a useEffect then after the animation Main.js loads. 
If all goes well I'll try to have a very basic demo video up in a day or so.

**Comment by AbhipsaGuru1012** [comment]
@kartikcho can I work on this issue?

**Comment by kartikcho** [comment]
There's an already open PR #366 on this although the author, @ashutosh1297, hasn't been active for a while. 
Maybe you can pick up their work and carry it to the finish line, starting with #365 since it's related to #366.
Otherwise you can pick up a different issue altogether, whichever is more comfortable for you.

**Comment by AbhipsaGuru1012** [comment]
@kartikcho I have made a PR. Please review and suggest if any changes are needed.

**Comment by Amoghtech** [comment]
Is this issue open?

**Comment by saadpasta** [comment]
@Amoghtech yes you can work on this one but try to use the above Lottie file provided by @pritishbarabde

**Comment by akshay-na** [comment]
@saadpasta  @kartikcho  Hey, sorry for tagging. Can you guys review my pull request? I tried to implement the Lottie preloader. Please let me know it requires some kind of fixes or any additions. The gifs are attached to the pull request.  Thanks
