### ISSUE TITLE
Convert Main.js into a functional component

### ISSUE THREAD

**Issue by SJellen** [saadpasta/developerFolio#363]
## Summary
Convert Main.js into a functional component

### What's new?
Convert Main.js into a functional component

### Motivation
As far as I can tell, almost all the components are functional components except for Main.js. For consistency it would be better if Main.js was also a functional component. 

### Additional context
Main.js is intertwined with the theme changer so thats the main hangup on making a quick fix.

**Comment by kartikcho** [comment]
Changed in https://github.com/saadpasta/developerFolio/commit/189dab9155929d360e21218b24a06d94fa2a5e9b
