### ISSUE TITLE
Extra landing space from header on smaller screens

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#367]
**Describe the bug**
On smaller screens, switching app theme with the header expanded adds extra space to the landing as visible in the screenshot.

**To Reproduce**
1. Go to https://developerfolio.js.org/
2. Use a smaller viewport, around 375 pixels wide.
3. Click on header menu and switch theme.
4. Observe the extra 'padding' on top of the lander section.

**Expected behavior**
No extra space in between header and landing

**Is this responsiveness Issue**
Possibly yes

**Screenshots**
![image](https://user-images.githubusercontent.com/48270786/118701895-de743c80-b831-11eb-93b0-368308a1bbb8.png)

![image](https://user-images.githubusercontent.com/48270786/118702021-05327300-b832-11eb-9f43-cf1a9e35e9dc.png)

**Desktop (please complete the following information):**
 - Browser : Observed on Firefox, haven't checked Chrome
 - Version : 88

**Additional context**
We should also look into the extra absurd padding in between sections on smaller screens as visible below.

![image](https://user-images.githubusercontent.com/48270786/118702104-2004e780-b832-11eb-8a84-dafa40c6654f.png)

**Comment by DuanLeeWatkins** [comment]
Hello, I do not see the issue when using chrome.

**Comment by kartikcho** [comment]
I tried it on Chrome and am still experiencing it. Can you provide the steps that you tried to check this @DuanLeeWatkins?
![image](https://user-images.githubusercontent.com/48270786/118847139-0d9ab480-b8eb-11eb-86fc-4c253ae9504c.png)

**Comment by ashutosh1297** [comment]
> On smaller screens, switching app theme with the header expanded adds extra space to the landing as visible in the screenshot.

I was able to replicate this using the steps from the issue on Chrome and Firefox as well. Looks like the whole thing is re-rendered when the theme is changed the first time and the greetings section is pushed down. It just stays there after the menu is closed. 



> We should also look into the extra absurd padding in between sections on smaller screens as visible below.

There is a 20px static top padding being given for every component container. We can maybe switch this to bootstrap based/dynamic padding to avoid weird looks on small screens.

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by kartikcho** [comment]
Sure @prsmahajan, take a look at the CSS for [header](https://github.com/saadpasta/developerFolio/blob/master/src/components/header/Header.js) and the [landing component](https://github.com/saadpasta/developerFolio/blob/master/src/containers/greeting/Greeting.js). Try to figure out why this is being caused, also read the discussion above for more context. 

Hope this helps you get started on it.

**Comment by gajanandh** [comment]
Hi,
 I was able to solve the issue by providing max-height to the React headroom wrapper, Please suggest if this can cause any issue
