### ISSUE TITLE
Change Tab Title on a Fork

### ISSUE THREAD

**Issue by mhowell11** [saadpasta/developerFolio#373]
Hello,

Thank you for creating this wonderful template. How do you change the metadata for the text next to the favicon on the tab? Even though I have changed my name in the JSON file you specified and the favicon, that text next to the favicon still says 'Saad Pasta Portfolio'. What file is that in? Thank you!

**Comment by naveen521kk** [comment]
You can simply edit https://github.com/saadpasta/developerFolio/blob/master/public/index.html#L51 and possibly other metadata's also.

**Comment by mhowell11** [comment]
Well that did the trick. Thank you @naveen521kk !
