### ISSUE TITLE
Codersrank username issue

### ISSUE THREAD

**Issue by zainkhalid91** [saadpasta/developerFolio#381]
I get the coders rank badge check to true but can't find the code where I have to write my coders rank username. It says you have to make changes in "src/containers/skillProgress/skillProgress.js:17:62". 
In skillProgress class I can't find the related code. 
For reference I am attaching the image. 
![Screenshot 2021-06-23 101138](https://user-images.githubusercontent.com/43206893/123039399-7d7ced00-d40b-11eb-89d5-0319b31c523d.png)

**Comment by mrtkp9993** [comment]
@zainkhalid91 How did you solve this problem?

**Comment by zainkhalid91** [comment]
I wasn't able to fix it so I skipped.
