### ISSUE TITLE
Image not loading 

### ISSUE THREAD

**Issue by RasenGUY** [saadpasta/developerFolio#384]
Hey guys so i tried this project out, but it seems the logo's don't seem to be loading 
It appears that the link to the image "/static/....../logo" is read as undefined,

When logging the school object, it appears that the link rests in `school.logo.default` instead of `school.logo`

The same occurs when loading the images on workExperience card, the link to the company rests in an object called logo with the key default which contains the link the image. 

the quick fix would be is to just load `school.logo.default` 

https://github.com/saadpasta/developerFolio/blob/1cf4547912e053418dd36fbc9d68a5817990cefd/src/components/educationCard/EducationCard.js#L28

and here to the same: 
https://github.com/saadpasta/developerFolio/blob/1cf4547912e053418dd36fbc9d68a5817990cefd/src/containers/workExperience/WorkExperience.js#L27 

`card.companyLogo.default`

Anyone experiencing the same issue or able to replicate the same issue ?

Wouldn't mind fixing this issue if you assign it to me 😃

**Comment by kartikcho** [comment]
Hey @RasenGUY , sorry for the late reply. Yes I see it on the deployed version too, even the color picker javascript for the cards seems to be broken. There's also some CSS issues like the logo font and stuff.

This is a concerning issue because the portfolio looks broken without it.
@naveen521kk I think I reported this before too and iirc you mentioned the PR that caused these breaking changes. Maybe that information will help in resolving this.

Assigning this to you @RasenGUY, let me know if you're able to deliver it until the next weekend, otherwise we can take this up due to it's priority.

**Comment by RasenGUY** [comment]
Ok I'm on it. I can look at the other issues, as well. don't know where to find it though so if you link it here I will take a look at the other things and fix them.

**Comment by kartikcho** [comment]
Sure, I'll tag you on other issues too once you're done with this one or if you find anything interesting, you can ask to take them up yourself!

**Comment by RasenGUY** [comment]
hey kartikcho, I've tried to reproduce the bugs, but it seems the issues were already addressed. I tried to push this website on a Vercel server but I kept getting into an error. During the build, I noticed I got compilation errors that didn't allow the app to build. I'm suspecting that these errors were/are playing a role in the current build @https://developerfolio.js.org/ 

so I fixed the errors -> see pull_request template. Hopefully this helps.

**Comment by kartikcho** [comment]
Hey @RasenGUY, I don't see any open PR that you're referring to. Could you link to it?

**Comment by RasenGUY** [comment]
One sec, submitting the PR as we speak

**Comment by RasenGUY** [comment]
just submitted the PR

**Comment by naveen521kk** [comment]
> @naveen521kk I think I reported this before too and iirc you mentioned the PR that caused these breaking changes. Maybe that information will help in resolving this.

I think the problem starts from https://github.com/saadpasta/developerFolio/commit/6aefe2a6e0372f28ca6109dc59b7417089a94944

Let me revert it and see whether it fixes things.
