### ISSUE TITLE
Video Background Request

### ISSUE THREAD

**Issue by LilCrispyVal** [saadpasta/developerFolio#389]
Is there a way to add in a video background? I know there is global color css but if there is any way to change the background not just color, that would be very helpful thank you!

**Comment by kartikcho** [comment]
Hey @LilCrispyVal that's a nice suggestion but for that we need to write CSS for it and find a place where we can insert the video background. 
If you can design how it would look and find a nice place for it somewhere on your local environment, you can add a screenshot here for discussion. If everyone else agrees, we'll make it a part of main branch!

I'll keep this issue open in case anyone else would like to take this up

**Comment by saadpasta** [comment]
@kartikcho we are following a minimalists design for now I guess background video is not something we need. I am open to adding your Videos as a component similar to blog component something like that

**Comment by kartikcho** [comment]
You're right, that is why I kept it up for discussion since adding video background can be tricky to fit with the rest of the design. 
You may close this or keep it open if someday a designer decides to contribute to the project, I'm okay either way.
