### ISSUE TITLE
Add new progress bar component

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#39]
Since this repo is gaining popularity, I think we should create more opportunities to work or contribute for new people who might be interested. What do you think @saadpasta ?

**Comment by saadpasta** [comment]
@kartik918 sound's great. But how can we achieve this?

**Comment by kartik918** [comment]
I was thinking something like adding more features but still keeping them optional for people who don't want them in their portfolio.

Example, that progress bar thingy for showing your proficiency in a language or technology, we could work on it as a feature. I don't like that so I wouldn't want that but for people who do, it'd make the portfolio better for them. 
Also this would make the portfolio unique for anyone who uses it.

**Comment by saadpasta** [comment]
@kartik918  Sounds Great. But I guess first we have make our deployment process easy and provide complete documentation on that. How can user deploy its site on Github Pages I have received lots of comments on this part

**Comment by kartik918** [comment]
Its very easy but node package manager must be installed to deploy on Github pages.
Look it up [here](https://reactgo.com/deploy-react-app-github-pages/) and write a documentation accordingly.

**Comment by saadpasta** [comment]
@kartik918 how can we achieve that optional thing do you have any idea.

**Comment by saadpasta** [comment]
> Its very easy but node package manager must be installed to deploy on Github pages.
> Look it up [here](https://reactgo.com/deploy-react-app-github-pages/) and write a documentation accordingly.

Ok Let's see

**Comment by kartik918** [comment]
> 
> 
> @kartik918 how can we achieve that optional thing do you have any idea.

I was thinking since all the components are individual, making them responsive and flexible enough to be able to work on their own would allow a user to make their own style of portfolio by removing the components they don't want.

i.e deleting the component files before using ``npm run deploy`` . 
Open to better solutions on this.

**Comment by saadpasta** [comment]
@kartik918 That's a great idea and we can keep it for the future I think first foremost important work is to add a contact form. What do you say?

**Comment by kartik918** [comment]
Contact "forms" are old and barely used, anyone who wants to contact anyone would email or use socials for quicker replies.
In my opinion we should work on a progress bar section for proficiency in skills first since that's a core of any portfolio (although I personally dislike them).

**Comment by saadpasta** [comment]
@kartik918 I have asked some people and recruiters they say that if they have opened someone portfolio and want to contact them then contact forms is the best way to contact them they don't have to email them personally or call them they can avoid that hassle. 

So I guess we both are correct in both way why not I start with contact Forms and you start with that progress bar (And Please make that Optional)

**Comment by kartik918** [comment]
It's alright, just different opinions. Also I'm kinda swarmed with work these days, I'll design it if I'm free.

**Comment by kartik918** [comment]
Feature added in #70.
