### ISSUE TITLE
Can't deploy Netlify

### ISSUE THREAD

**Issue by LilCrispyVal** [saadpasta/developerFolio#393]
This is rather confusing, for my github, (as you can click on my profile to check), I'm not able to deploy it on netlify, I'm trying every single thing to do.

**Comment by LilCrispyVal** [comment]
Is it possible to make a tutorial as well? This is really complicated as I rather not do gh-pages anymore, I'm scared since my website is public sourced, anyone can join in.

**Comment by kartikcho** [comment]
Hey it's actually quite simple and would only take like 5 mins. Check [this](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) guide out, it's very descriptive. If you still can't figure it out, reach out to me through mail and I can guide you on Discord or something.
