### ISSUE TITLE
Add a "Buy me a coffee" button to portfolio

### ISSUE THREAD

**Issue by AbhishekBhatt072003** [saadpasta/developerFolio#395]
What if we add a "Buy me a coffee" button at the end of the folio near the contact-me sections. Using this feature we can redirect users to an external website where users can donate a sum of money (whatever they wanted ) for the hard and good work by the folio owner.

If you want you can check this feature over here:-
[https://abhishekbhatt072003.github.io/Portfolio/#contact](url)

**Comment by saadpasta** [comment]
That's really great but I don't think that’s necessary now. 
Thanks @AbhishekBhatt072003
