### ISSUE TITLE
Regarding not working of open source option mentioned in header of portfolio

### ISSUE THREAD

**Issue by srishti3418** [saadpasta/developerFolio#397]
When I made change in portfolio.js to make my custom portfolio and forked and pushed the changes to github and after deploying it on netlify. Open source section is not visible. Can you tell me why is this happening??

**Comment by arghyadeep99** [comment]
It's possible you didn't the .env file step properly. Can you check and verify?

**Comment by kartikcho** [comment]
@srishti3418 is your issue resolved? 
Thanks for helping out Arghyadeep!
