### ISSUE TITLE
Font variant ligature in logo-name is broken

### ISSUE THREAD

**Issue by sungyeonu** [saadpasta/developerFolio#400]
font-variant-ligatures is broken. 

**Expected behavior**
font ligature should work with nice cursive style 

**Is this responsiveness Issue**
NO

**Screenshots**
![image](https://user-images.githubusercontent.com/47223114/131382933-394096f5-321d-4e5e-aa9f-1eaf616bc7c1.png)

should look like 
![image](https://user-images.githubusercontent.com/47223114/131382969-2ef8e6b2-7993-4939-a9bf-6447a97de4f0.png)

**Comment by naveen521kk** [comment]
This exists on the main project page also. I remember fixing it in https://github.com/saadpasta/developerFolio/commit/18c1a9fd72f89bf91d5e45bf31d7c36b5df88e6c but not sure what happened.

**Comment by kartikcho** [comment]
@naveen521kk probably happened in https://github.com/saadpasta/developerFolio/commit/18c1a9fd72f89bf91d5e45bf31d7c36b5df88e6c, I see the font file has been touched.

**Comment by naveen521kk** [comment]
I think https://github.com/saadpasta/developerFolio/commit/189dab9155929d360e21218b24a06d94fa2a5e9b, I could see it touched the font file.
