### ISSUE TITLE
Can't Deploy Without Access Token Being Revoked

### ISSUE THREAD

**Issue by ariel-frischer** [saadpasta/developerFolio#403]
**Describe the bug**
When I follow instructions, somehow the access token from my `.env` file gets added to git remote repo, causing github to revoke the access token. My `.gitignore` definitely has `.env` added to it, so I'm not sure how this is happening, perhaps the build/deploy stage is somehow adding the token to the remote repo.
Email:
"We noticed that a valid OAuth, GitHub App or Personal Access Token of yours was committed to a GitHub repository. Disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data. As a precautionary measure, we have revoked the token. You will need to generate a new token for the app to authenticate to GitHub. "

**To Reproduce**
Add github token to .env, then do `yarn deploy`

**Expected behavior**
Deploy without causing github to revoke personal access token.

**Comment by kartikcho** [comment]
It is hard to debug this without more information. 
A bunch of users have faced this problem while deploying this project and we have extensive docs and wiki just to help with this. I would suggest read the docs and the past issues again to see if you can resolve your issue.
