### ISSUE TITLE
Kaggle profile

### ISSUE THREAD

**Issue by MrAsimZahid** [saadpasta/developerFolio#405]
In social connections, please add [kaggle](https://www.kaggle.com/) profile attachment like github.

It's like a GitHub profile for data scientists and AI engineers.

Thanks.

**Comment by kartikcho** [comment]
Sounds like a great addition but unfortunately I haven't used it personally so I don't have much ideas on how we could add it. 
Do you know if they provide userdata through an API or something?

Also we would need to finalize a design for the component before proceeding with any PRs.

**Comment by MrAsimZahid** [comment]
For starting, we can do is add a kaggle button in socials.
https://mrasimzahid.github.io/

**Comment by kartikcho** [comment]
I don't see it in your deployed version, unless you were suggesting to add it there. This sounds like a good start, I'll add the option for a Kaggle profile to social links.
We should still continue discussion on adding a component for displaying user's Kaggle data and stats.
