### ISSUE TITLE
Lotties/graphics should be centered in all sections

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#413]
The illustrations or Lotties look off in their respective section layouts and should be center aligned to blend well with the rest of the page.

**Screenshots**

The new layout should have the lotties centered instead of being left aligned as in screenshot below.

![image](https://user-images.githubusercontent.com/48270786/133893025-9fd6f4a4-35e3-429d-b0a0-d2162da15d27.png)

**Comment by saadpasta** [comment]
@kartikcho can you provide example of what you mean

**Comment by kartikcho** [comment]
My previous screenshot doesn't exactly describe the issue clearly but the graphics look more 'off' in other sections like the example below:

(The blue is the center of the layout)

![image](https://user-images.githubusercontent.com/48270786/133921425-52363eb8-a13f-4d16-ac06-d67a3aa407a9.png)

Looking at the CSS, it does have equal margin horizontally but it doesn't look that way (might be overthinking).

**Comment by sadapasta** [comment]
ahhhh okay 👌 ✅

**Comment by nayabatir1** [comment]
@saadpasta may I help

**Comment by saadpasta** [comment]
Yeah man go for it
