### ISSUE TITLE
Leet Code profile social link

### ISSUE THREAD

**Issue by MrAsimZahid** [saadpasta/developerFolio#414]
## Summary
Leet code is one of the developer's profiles that shows proficiency in DSA. 

### What's new?
Request for leetcode profile link in socials. It's a gem in developer's profile and recruiters do look for it. Even Google recruiter's explicitly mentions to add leet code profile on the resume.

Please add leet code social link.
Thanks.

Example profile link:
https://leetcode.com/mrasimzahid/

**Comment by tabassum2507** [comment]
Would love to work on it!

**Comment by MrAsimZahid** [comment]
@tabassum2507 @nayabatir1 
Pull requests are welcome.

Please review this issue to understand replicate here.
https://github.com/saadpasta/developerFolio/issues/405
Thanks.

**Comment by kartikcho** [comment]
Font awesome doesn't support leetcode icon and we shouldn't add extra icons for stuff it doesn't support (if we start going down this road, there won't be an end to the amount of social profile icons we could add). We should leave that option to customize for the end user.

**Comment by nayabatir1** [comment]
> Font awesome doesn't support leetcode icon and we shouldn't add extra icons for stuff it doesn't support (if we start going down this road, there won't be an end to the amount of social profile icons we could add). We should leave that option to customize for the end user.

@kartikcho then why created an issue in first place?

**Comment by kartikcho** [comment]
You can see that it wasn't one of the maintainers who created it.
