### ISSUE TITLE
Switch font sizes to using 'rem' units instead of pixels or 'em'

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#456]
## Summary
We should switch to using 'rem' units instead of the inconsistent pixel values for improving accessibility and following accessible web design best practices.

### What's new?
The font sizes should switch to 'rem' but the final design should remain almost completely similar to before.
For conversion reference, 16px = 1rem.

### Motivation
Improving accessibility and following accessible web design best practices.

**Comment by SpectralGT** [comment]
Assign me this.
