### ISSUE TITLE
Increase margin for buttons

### ISSUE THREAD

**Issue by rajkumaar23** [saadpasta/developerFolio#47]
Screenshots : 
![FAE9D2CE-45C5-4C03-9693-83063B010A8E](https://user-images.githubusercontent.com/37476886/72340740-b67d4200-36ee-11ea-9c9b-4fdc825c68fc.png)

These two buttons need to have a little more margin.

**Comment by kartik918** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/48270786/72353066-68c20300-3709-11ea-8a96-59147d23d5fe.png)
Looks fine on firefox, maybe a safari issue?

**Comment by rajkumaar23** [comment]
No, try the device as iPhone SE

**Comment by rajkumaar23** [comment]
![image](https://user-images.githubusercontent.com/37476886/72353603-56949480-370a-11ea-9ed1-40e16ffb380b.png)

**Comment by kartik918** [comment]
Great find! Adding ``font-size: 13px;`` at width lower than 320px should make it responsive again. 
Your PR fixing this would be appreciated.

**Comment by rajkumaar23** [comment]
@kartik918 `13px` was still looking bad, so fixed it with `12px` 🤙️
