### ISSUE TITLE
Option to switch theme

### ISSUE THREAD

**Issue by adarsh-goel** [saadpasta/developerFolio#472]
## Summary
**First of all shout out to you and your team for such great work <3
**I would like to request you to add option to change theme like** https://github.com/ashutosh1919/masterPortfolio/blob/master/src/theme.js**
**because write now the background is plain white i would like to make it look cool like the example stated**
### What's new?
**It will make it easier to customise plus switch by changing selected variable.**
**like this https://github.com/ashutosh1919/masterPortfolio/blob/master/src/theme.js#L122**
### Advantages
**It will make things look cool and easy to manage**

**Comment by adarsh-goel** [comment]
pick it up as in, I am not familiar with js I only know python and c++ only tbh

**Comment by kartikcho** [comment]
We do support theming, much more extensively by using scss. Checkout the [global scss variables config file](https://github.com/saadpasta/developerFolio/blob/master/src/_globalColor.scss) to tweak things according to your usecase @adarsh-goel
