### ISSUE TITLE
Github and Medium failed to load

### ISSUE THREAD

**Issue by bobbyirawan09** [saadpasta/developerFolio#477]
**Summary**

I had a problem when using getting data from Github and Medium. Already follow the documentation, add access token for Github, use my Medium and Github username. But it still shows an error, I don't think my changes cause the bug. Can you please help check this issue? Thank you.

For the record, I usually deploy from the command line `npm run build` to deploy to production. Please refer to the information below of the error log

Screenshot:

![CleanShot 2022-03-21 at 14 00 46](https://user-images.githubusercontent.com/21231279/159212194-871bca10-4de9-4bb5-a194-d26b3fc49b0e.png)

Github project:
https://github.com/bobbyirawan09/developerFolio

Website:
https://bobbyirawan09.github.io/developerFolio/

I would appreciate any help I can get. I had zero experience using React so I am barely able to know the root cause.

**Comment by niharpatel1999** [comment]
did you make changes in the .env file ?
add your github username and token in that file 

run npm install
run npm start

this should clear your error.

**Comment by kartikcho** [comment]
Could you also confirm if you can see fetched data in local dev? If not then do as suggested above (and in the docs)

**Comment by bobbyirawan09** [comment]
already solve the problem, here are the steps

- I clone the new project on the main repository. Try it and its works
- Copy the whole project and paste it on my own. The changes will appear. Try it and its works
- Build the production and now its working fine

Thanks for all your reply, sorry for causing the trouble
