### ISSUE TITLE
Add standard issue and PR templates

### ISSUE THREAD

**Issue by rajkumaar23** [saadpasta/developerFolio#48]
- Need to have standard Issue and PR templates for the repository, so that it’s uniform for everyone.

**Comment by rajkumaar23** [comment]
@saadpasta What do you think about this ?

**Comment by saadpasta** [comment]
@rajkumaar23 I guess for now we don't have that much traffic that we need a template for PR and issues but surely we can do it for the Future.
Thanks ❤️
@kartik918 what's your opinion

**Comment by kartik918** [comment]
I guess for now we don't have that much traffic that we need a template for PR and issues but surely we can do it for the Future.

I was going to say exactly the same saadpasta. We'll work on community guidelines and PR templates when the repo hits more than 10 or 15 contributors. Thanks for the idea.

**Comment by kartik918** [comment]
Since the number of contributors has significantly increased, we may need to address this issue soon. What do you think @saadpasta ?

**Comment by saadpasta** [comment]
Yeah, I also think we create a template

**Comment by rajkumaar23** [comment]
@saadpasta Cool then, can you please create the template and lets close this issue ?

**Comment by kartik918** [comment]
Only an owner can add these templates because they have settings access to the repo so I'm assigning this to you Saad.

**Comment by saadpasta** [comment]
@kartik918 @rajkumaar23 Sorry I was sick for quite a few days. So couldn't work on this. 
Adding this as soon as possible.

**Comment by kartik918** [comment]
It's alright, let's bump this up to P1 because our project is getting shared on socials and more people will be coming in to contribute @saadpasta.

Also, let me know what you think about setting up priority labels.

**Comment by saadpasta** [comment]
solved #128 #129
