### ISSUE TITLE
Start local dev server issue

### ISSUE THREAD

**Issue by Guohao91** [saadpasta/developerFolio#485]
hi, Saad Pasta and Kartik

This is my first time to build up my personal portfolio on site, and i like your layout design like the scroll down browse way. 
While I was doing this step, 

**# Start a local dev server
npm start**

I get errors like the following:
![Screenshot from 2022-04-23 20-16-471231](https://user-images.githubusercontent.com/54188732/164955215-385556b4-27ff-47e2-be0f-7bd4cfb10958.png)

I tried with different ways but they don't work properly, would you please help for this? 
I really desire to achieve my first portfolio site, please any tip! Thank you in advance.

My OS is ubuntu 20.43 64-bit

npm version : 6.14.4
node version : V10.19.0
git version:  2.25.1

**Comment by EndLess728** [comment]
You have to put your github username and medium username in .env file, It is required to run the project .

However there is a workaround you can do for medium if you don't have medium account.

Do below change in Fetch.js file on line number 98.

Replace this code 

`if (MEDIUM_USERNAME !== undefined)`

with this one
```
if (
  MEDIUM_USERNAME !== undefined &&
  MEDIUM_USERNAME !== "YOU MEDIUM USERNAME HERE"
)
```

**Comment by Guohao91** [comment]
@EndLess728 
Oh hi, thank you so much for your answer! I believe this would work very well later.
but now, i find actually there is an issue makes me stuck here: 
![Screenshot from 2022-04-24 14-57-15](https://user-images.githubusercontent.com/54188732/164998366-458aa8cf-0520-4c05-94bf-3e59e16aa4bc.png)
so when i install dependencies by "npm install", it shows up here and i've changed the authority from root to my username: yghrobotics.
![Screenshot from 2022-04-24 15-02-06](https://user-images.githubusercontent.com/54188732/164998571-e526137b-d043-458b-9105-5218e5d84d60.png)

And my current developerFolio folder has these files,
![Screenshot from 2022-04-24 14-30-50](https://user-images.githubusercontent.com/54188732/164998402-99033311-5c1c-4ba2-9ed2-e6cbc1ac07f5.png)
and in the env.example file, i have:
![Screenshot from 2022-04-24 14-31-07](https://user-images.githubusercontent.com/54188732/164998458-b6d0e458-2fd9-4a06-976b-ab88ad788a70.png)

Would you please fix this annoying issue for me please?

**Comment by EndLess728** [comment]
Follow these steps .

https://github.com/saadpasta/developerFolio#how-to-use

The third step is important. You have to make a copy of env.example to .env and then you have to put your github token , username there 

# For Linux
cp env.example .env

And instead of npm , use yarn because i also faced issues while installing packages using npm .

**Comment by Guohao91** [comment]
@EndLess728 
Okk, yea! I do follow the instructions but i am just new here, so let me try every step one by one.
![Screenshot from 2022-04-25 20-05-20](https://user-images.githubusercontent.com/54188732/165212117-8c1ea42f-4681-408a-a190-218b4b7af39d.png)
so, here as the recommend said, i don't select any scope but just generate a simple token, right?
![Screenshot from 2022-04-25 20-06-19](https://user-images.githubusercontent.com/54188732/165212244-06a5a729-2104-4239-ac87-68c09a177c03.png)
and I could actually set the expiration as "no expiration", is that right?

Thanks!
