### ISSUE TITLE
Is there a way to edit after deploying?

### ISSUE THREAD

**Issue by madisoncarsan** [saadpasta/developerFolio#495]
**Describe the bug**
Can't find a way to edit after deploying

**Comment by kartikcho** [comment]
- Make the changes in your local repository
- Push it to a branch on github
- Redeploy with whatever tools you're using

**Comment by madisoncarsan** [comment]
@kartikcho - thanks for the help

Maybe I am missing something, but every time I go through the deployment process, my branch loses most of the files that I have and ends up looking like this:
<img width="946" alt="Screen Shot 2022-07-19 at 4 46 10 PM" src="https://user-images.githubusercontent.com/69589527/179866663-8f166ce0-c8e9-4335-869c-cdfe61ace834.png">
