### ISSUE TITLE
Heroku Deployment H10 error

### ISSUE THREAD

**Issue by janie-lee-developer** [saadpasta/developerFolio#497]
**Describe the bug**
Heroku Deployment H10 app crash error
I am trying to deploy on Heroku. The app is successfully built. But when I try to load the page, the app crashes w/ H10 error. Pls advise what could resolve this? Thank you in advance.
<img width="1449" alt="Screen Shot 2022-06-20 at 1 58 03 AM" src="https://user-images.githubusercontent.com/58411107/174534619-7b12a9d9-934c-4a8c-ad0d-e58d8e146526.png">

**Comment by kartikcho** [comment]
Sorry for the super late reply, is this still crashing @janie-lee-developer ?
