### ISSUE TITLE
Better styling for medium resolutions

### ISSUE THREAD

**Issue by 9inpachi** [saadpasta/developerFolio#5]
The site as it is now does not look very good at medium resolutions.
Specifically the padding and font size do not look optimal.
Tested on resolutions 1280 x 720 and 1024 x 768.
![image](https://user-images.githubusercontent.com/36920441/68463663-f9bfbe00-0230-11ea-8fd3-b0cde1efee77.png)

I will try to add a fix for this.

**Comment by saadpasta** [comment]
Thank You so much @9inpachi.  Appreciate a lot. If you could help me fix this that would be wonderful. And thanks once again
