### ISSUE TITLE
Error while Package Installation 

### ISSUE THREAD

**Issue by shehwar-ahmad** [saadpasta/developerFolio#503]
I used npm install and npm install --force to install the packages but got errors for both times. 

npm version: 8.13.2
node version: 17.7.2

Errors are as follows: 

![error](https://user-images.githubusercontent.com/50246426/178083083-21392261-e7a0-4445-b34a-b01200feb7ed.png)

What could be the issue? Is it the node or npm version

**Comment by SR-Sunny-Raj** [comment]
Hey @shehwar-ahmad can you please explain how you fixed this problem as I'm also getting the same errors when doing npm install

**Comment by shehwar-ahmad** [comment]
@SR-Sunny-Raj This was due to the Node Version. Please check the documentation for the exact Node Version.
