### ISSUE TITLE
GitHub 'Available for Hire' is deprecated

### ISSUE THREAD

**Issue by camipozas** [saadpasta/developerFolio#507]
Hello!

Sorry for don't use the issue template, I think this is a question than an issue. So, how can I set I'm hireable in GitHub? I was looking but the option is deprecated :( Thanks!

**Comment by kartikcho** [comment]
Sorry for the super late reply and it's alright to not use the template for questions.
You're right, [GitHub jobs is deprecated](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/what-does-the-available-for-hire-checkbox-do) so you can't set it in GitHub.

We could make it tweakable in `portfolio.js` so we don't fetch it from the gh profile and instead get it from the schema.
It's a straightforward task, would you like to take it up @camipozas ?

**Comment by saiteja13427** [comment]
I would want to take this up @kartikcho

**Comment by camipozas** [comment]
I'm sorry for the delay, I was in it. If it is already assigned, nothing happens. Or I can take another :) @kartikcho

**Comment by kartikcho** [comment]
Oh I'm sorry. @saiteja13427 if you've not started yet we can assign it to @camipozas and you could review it.
Always great to have a new contributor!

**Comment by saiteja13427** [comment]
Sure @kartikcho, I would love to review :-)

**Comment by kartikcho** [comment]
Alright @camipozas, assigning to you!

**Comment by camipozas** [comment]
Hello! recently I raise the [PR](https://github.com/saadpasta/developerFolio/pull/519)

**Comment by saiteja13427** [comment]
Gave my comment on the PR!
