### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by reeshabhranjan** [saadpasta/developerFolio#509]
**Describe the bug**
`npm install` is failing

**To Reproduce**
1. Clone the repository
2. `cd` into the repository
3. `cp example.env .env`
4. `npm install`

**Expected behavior**
The build should pass

**Is this responsiveness Issue**
NO

Logs:
[https://gist.github.com/reeshabhranjan/c1a0528cfb17991d42b155d16b9531b9](https://gist.github.com/reeshabhranjan/c1a0528cfb17991d42b155d16b9531b9)

**Comment by ParamChordiya** [comment]
Found a roundabout to this problem, u can use `yarn install` instead of `npm install` this worked for me.
