### ISSUE TITLE
Add repo size conversion to github repo cards

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#525]
Cards currently only show repo sizes in kb. This looks ugly when a repo size is in mb or greater.

We should add size conversion and format the output appropriately

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by kartikcho** [comment]
Sure!
I was keeping this for hacktoberfest so I would suggest opening the PR on October 1 if you would like to get the contribution counted.

**Comment by Vinitvh** [comment]
Okay. Do you want the size in MB to be absolute value or rounded off to a certain decimal place?

**Comment by kartikcho** [comment]
Single decimal point should be good enough
