### ISSUE TITLE
Remove Proficiency Section

### ISSUE THREAD

**Issue by Dun-sin** [saadpasta/developerFolio#527]
## Summary
Remove the Proficiency section that shows how good someone is in a particular section

### Motivation
This section doesn't really help because there's no actually way to calculate that

### Additional context
![image](https://user-images.githubusercontent.com/78784850/192538846-10dd0b4b-18b8-4155-95b3-d5b1d4553c6f.png)

**Comment by kartikcho** [comment]
I agree with you and I personally don't like skill bars for the same reason too but the decision to remove the section altogether is subjective.
Some people do prefer it and we can't remove it for everyone.

However, you can hide it on your portfolio by [turning it off in the portfolio schema](https://github.com/saadpasta/developerFolio/blob/master/src/portfolio.js#L153). Hope that helps!
