### ISSUE TITLE
Add icon for clarity

### ISSUE THREAD

**Issue by Dun-sin** [saadpasta/developerFolio#528]
## Summary
Add icons to the dark mode switch tab

### What's new?
It adds an icon for light mode and dark mode to the existing component to show it present status

### Motivation
when I first got to the website, I didn't understand what the switch was for until I clicked it, not a good user experience

### Additional context
![image](https://user-images.githubusercontent.com/78784850/192540127-3d99fae2-3c4d-44ea-ac9e-d6e743c73ac1.png)

**Comment by kartikcho** [comment]
Yeah that's a great idea! We can add an icon inside the switch component (maybe ☀ and 🌙 emoji?) to make this clear.

**Comment by kartikcho** [comment]
Would you like to take this up @Dun-sin ?

**Comment by Dun-sin** [comment]
Yes thank you🙌🏽
