### ISSUE TITLE
Fix pull request template

### ISSUE THREAD

**Issue by Dun-sin** [saadpasta/developerFolio#532]
I noticed that the pull request template doesn't work, it's because it's in a folder, it should be in the root folder of `.github` and not the `Pull Request Template` folder that it's currently in

**Comment by kartikcho** [comment]
Good catch. Would you like to take this up too?

**Comment by Dun-sin** [comment]
> Good catch. Would you like to take this up too?
> 

Na, I don't want to be too stingy😂 give it to anyone who wants

**Comment by Njong392** [comment]
Could I tackle this? 👀

**Comment by raji2004** [comment]
i would love to be assigned this issue

**Comment by Dun-sin** [comment]
@kartikcho seems like @Njong392 asked first, I can give it to them

**Comment by kartikcho** [comment]
Sorry @raji2004! You can take a look at other available issues. 
Assigning this to you @Njong392
