### ISSUE TITLE
[BUG] remove extra space on dark mode switch

### ISSUE THREAD

**Issue by Dun-sin** [saadpasta/developerFolio#534]
**Describe the bug**
There's a tiny space at the end of the header

**Is this responsiveness Issue**
No

**Screenshots**
![image](https://user-images.githubusercontent.com/48270786/193418251-9b5d5b50-044c-4c6f-b0c9-8b6573f2b793.gif)

**Comment by Dun-sin** [comment]
@kartikcho I don't think there's an actual problem here, can you give a full screen

Because this is what i see, and it seems fine to me

![image](https://user-images.githubusercontent.com/78784850/193423416-ade240a5-9489-4b83-8c05-488e0dfda0ad.png)

**Comment by kartikcho** [comment]
It's not visible on dark mode switch, check light mode switch closely to see the difference (screenshot below)

![image](https://user-images.githubusercontent.com/48270786/193448486-88255be9-f78c-4316-9ea9-0267ab361333.png)

It's a very minor detail and didn't warrant an issue tbh but lets fix it now 😅 @Dun-sin

**Comment by Dun-sin** [comment]
> It's not visible on dark mode switch, check light mode switch closely to see the difference (screenshot below)
> 
> ![image](https://user-images.githubusercontent.com/48270786/193448486-88255be9-f78c-4316-9ea9-0267ab361333.png)
> 
> It's a very minor detail and didn't warrant an issue tbh but lets fix it now 😅 @Dun-sin 
> 

Wow🤣
