### ISSUE TITLE
Upgrade Node as v12.x has been deprecated by Vercel

### ISSUE THREAD

**Issue by kartikcho** [saadpasta/developerFolio#540]
Looks like vercel deprecated node 12 according to this [build log](https://vercel.com/saadpasta/developer-folio/7Smu8x9pnZKARHwAmsB1fu8cYaeT).
Should upgrade it to either the latest or nearest stable version without breaking too many things

**Comment by kartikcho** [comment]
@saadpasta this is urgent
I can't config this. You'll have to fix this from the project settings on vercel. Until then no previews and deploys would work

**Comment by SR-Sunny-Raj** [comment]
Please I request you to fix it asap as most of the dependencies are not getting downloaded and also the build is getting failed.

**Comment by sadapasta** [comment]
@kartikcho updated to 14 in vercel can you try again

**Comment by kartikcho** [comment]
@saadpasta could you add me to the project on Vercel? I think I'll need to manually trigger redeploys

**Comment by kartikcho** [comment]
or @sadapasta, whichever one you're active on now :P
