### ISSUE TITLE
Hosting on Panel such as plesk?

### ISSUE THREAD

**Issue by Lexian-droid** [saadpasta/developerFolio#543]
Hello, I just bought a new domain name, and I was hoping to put this as my website, I was wondering, is it possible to host this via Plesk? I tried doing so, however it gives me a lot of boxes, like "custom variables", "Application root" "document root" stuff like this, and I'm just unsure how to do it.

If anyone could lend a hand, or give me some information, if this is possible or not, it would be greatly appreciated, I know that this program does use node.js, and I do have that installed. I just don't know what you do to set it up. Thanks.

**Comment by kartikcho** [comment]
I have zero experience with Plesk tbh but they must have some docs or a guide to help out with setup.
I dont know how it works but normally you would need to create a build of the app (using `npm run build`) and host it on the platform to deploy it.
Read through the [docs](https://github.com/saadpasta/developerFolio#table-of-contents) maybe you'll figure it out. I'll keep the issue open for a while jic someone has used it before and can help out
