### ISSUE TITLE
Update React Easy Emoji

### ISSUE THREAD

**Issue by yunussukrugulten** [saadpasta/developerFolio#570]
### Summary

Hello,

The baseurl(twemoji.maxcdn.com) in the react easy repository has not been working for a while and cdn cloudflare address is used instead of twemoji.maxcdn.com.

I recommend you update.
![SaadEmojiError1](https://user-images.githubusercontent.com/63670220/211390563-eaa54c05-6001-4bcf-9a53-7deae1d87132.png)
![SaadEmojiError2](https://user-images.githubusercontent.com/63670220/211390566-1e797130-861a-47e6-b184-ea42a7a4d420.png)

### What's new?

You can get the update from the link

https://github.com/appfigures/react-easy-emoji

Changelog

https://github.com/appfigures/react-easy-emoji/commit/e6c3949416838fdf2dfebca98e625cbbd6ae99c5

### Motivation

To see emojis :)

### Additional context

If you are using a content security policy, I recommend updating the new address with twemoji.maxcdn.com, otherwise your emojis will not be visible.

**Comment by ajaymajmudar** [comment]
Having the same emoji issue. How does one fix this with the update? i tried npm install --save react-easy-emoji and that doesn't work.

**Comment by saadpasta** [comment]
@yunussukrugulten is there any other way of doing it maybe through dependency update or should we wait until they resolve this issue

**Comment by yunussukrugulten** [comment]
> is there any other way of doing it maybe through dependency update or should we wait until they resolve this issue

Hello,

Frankly, I'm following the React Easy Emoji repo for the moment. When I couldn't see the emojis on my own website, I immediately looked on github and saw that the repo was updated.

I don't know if twemoji.maxcdn.com will be reactivated or remain inactive, but I needed to take an action for the emojis to work and I acted according to the repo and made the necessary updates.

Emojis now appear seamlessly on my website.

My website: yunussukrugulten.com

I leave the decision to you.

Regards
