### ISSUE TITLE
Setup Nextjs with separate build on the root folder

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#571]
Setup Nextjs project with separate build and add prettier and Eslint. We need to setup in on the root folder so we can move components one by one to our Next Project.

**Comment by ahmadjafari86** [comment]
Hi , may i help you?

**Comment by MuhammadZeeshanAshraf** [comment]
@saadpasta what are ESLint that we should configure in the project?

**Comment by MuhammadZeeshanAshraf** [comment]
@saadpasta which target branch should we use for the pull request?

**Comment by saadpasta** [comment]
@MuhammadZeeshanAshraf Let's use the Nextjs one nextjs provide with one you can use anything you want for now I would update that later on

**Comment by saadpasta** [comment]
@ahmadjafari86 sure you can create a PR for us even if it's not merged I would add you as a contributor for your efforts

**Comment by saadpasta** [comment]
@MuhammadZeeshanAshraf Should I assign you this ticket we need to work on it ASAP and get this done

**Comment by MuhammadZeeshanAshraf** [comment]
> 

I believe separate branch will be a better appraoch

**Comment by MuhammadZeeshanAshraf** [comment]
> @MuhammadZeeshanAshraf Should I assign you this ticket we need to work on it ASAP and get this done

Sure

**Comment by joshi-kaushal** [comment]
I would love to help on this. Is this issue still live?
(I saw other issues too, but this one needs to be fixed on priority)

**Comment by saadpasta** [comment]
@joshi-kaushal You can start on this @MuhammadZeeshanAshraf is already working but would love to see your implementation also

**Comment by saadpasta** [comment]
Completed
