### ISSUE TITLE
Add Twitter Timeline

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#63]
Adding a twitter timeline would embed the latest tweets of the user. Making it optional would be better. This would make the site look more good with latest feed updated.

**Comment by saadpasta** [comment]
Yes, Good Idea 😀. Are you working on it.

**Comment by naveen521kk** [comment]
I will try on it. Let it be optional and API entered by the user in src/protofolio.js

**Comment by naveen521kk** [comment]
I am trying to use https://github.com/saurabhnemade/react-twitter-embed in this project. Can I.

**Comment by saadpasta** [comment]
Yeah, you can. Let's see what we get but make sure to update the readme and do the changes in portfolio.js for the user.

**Comment by naveen521kk** [comment]
Add this to https://saadpasta.github.io
