### ISSUE TITLE
Automatically add latest blog post

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#69]
Adding automatic blog post would be better. If the user writes a new blog post it should automatically come out in this Page. Better using any Rss feed or Blogger API.

**Comment by kartik918** [comment]
Are you working on this @naveen521kk so I can assign this to you.

**Comment by naveen521kk** [comment]
Yes I am. You can assign me.

**Comment by naveen521kk** [comment]
Working further on this requires to use[ CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). I know that Github Pages automatically sets a CORS header and allows cross-origin requests. But while deploying it on Netlify or testing Locally I had to manually set the headers. Shall I create the configuration for Netlify?

**Comment by saadpasta** [comment]
@naveen521kk which API are you requesting

**Comment by naveen521kk** [comment]
I think of directly get the RSS feed and parse it. For getting the RSS feed CORS headers must be enabled. The link of RSS feed will be entered in protofolio.js.

**Comment by kartik918** [comment]
Add it but comment it out and add something like a note to un-comment it if deploying on Netlify.
Primary users generally prefer to deploy on gh pages than Netlify so this can be enabled per user.

**Comment by naveen521kk** [comment]
It is out of the scope of this project and it not very efficient. So closing it.
