### ISSUE TITLE
Use signature like font for the site logo

### ISSUE THREAD

**Issue by 9inpachi** [saadpasta/developerFolio#7]
Using a handwriting signature like font makes the logo unique and attractive.
![image](https://user-images.githubusercontent.com/36920441/68544292-798d8a00-03e3-11ea-9eed-fabbac0fa235.png)

**Comment by saadpasta** [comment]
Do you think it will look good with the rest of the UI

**Comment by 9inpachi** [comment]
Yes. Since it makes the logo unique. The normal font looks too plain.
![image](https://user-images.githubusercontent.com/36920441/68589411-a4dcab80-04ad-11ea-91e5-d6ab03ca06fb.png)

**Comment by saadpasta** [comment]
Great,  Thank you so much can you open a merge request for that.

**Comment by saadpasta** [comment]
@allcontributors add @9inpachi for ideas
