### ISSUE TITLE
Switch to different license

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#72]
Recently I've seen a rise in the number of people using our portfolio (which is great news). 

This also comes with people who are not using this for their personal use but instead wrapping it as their own work and getting clout for the work put by so many in this.

I strongly suggest we shift to a less flexible license than MIT (which only requires the person to credit the original work but have all other rights). 
I hope this would help reduce the number of incidents like these as the project was built for personal use and not personal gain. @saadpasta

**Comment by saadpasta** [comment]
@kartik918 Yes I also think so what license do you suggest.

**Comment by kartik918** [comment]
I looked up from the options we have and GNU GPLv3 seems like the best one for our case. Read more about it and other licenses [here](https://choosealicense.com/licenses/)

Let me know if you think the same and I'll update it with a PR @saadpasta

**Comment by saadpasta** [comment]
yeah i guess GPLv3 is fine
