### ISSUE TITLE
Incorrect Resume Upload Path in Documentation

### ISSUE THREAD

**Issue by jingchenyc** [saadpasta/developerFolio#733]
### Describe the bug

The README documentation suggests uploading the resume pdf to src/containers/resume and renaming it to resume.pdf. However, the correct path should be src/containers/greeting.

### Steps to reproduce

1. Go to the README documentation in the developerFolio repository.
2. Look for the "Resume upload" section.
3. Follow the instructions to upload the resume.
4. The path specified (src/containers/resume) does not match the actual folder structure, which should be src/containers/greeting.

### Expected behavior

The correct folder path for uploading the resume should be src/containers/greeting, not src/containers/resume. Updating the README would help avoid confusion for users.

### Is this responsiveness Issue

NO

### Screenshots

N/A

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by nishantdecode** [comment]
@jingchenyc can you please assign this issue to me?

**Comment by jingchenyc** [comment]
issue's PR have already merged to the branch
