### ISSUE TITLE
Resume button in nav bar

### ISSUE THREAD

**Issue by Jolomi-Tosanwumi** [saadpasta/developerFolio#737]
### Describe the bug

Resume button in nav bar not redirecting to "DOWNLOAD MY RESUME" button.

### Steps to reproduce

1. Go to 'navigation bar'
2. Click on 'Resume'

### Expected behavior

Redirect to "DOWNLOAD MY RESUME" button.

### Is this responsiveness Issue

YES

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by Arihant-Singh-Rana** [comment]
Greetings of the day !!
I just wanted to know that can you assign this issue to me!
I want to contribute in this project as a part of my Hacktober Fest participation
