### ISSUE TITLE
Better content and styling for contact page

### ISSUE THREAD

**Issue by iadeelzafar** [saadpasta/developerFolio#8]
* Refactor `Contact Me` hyperlink text to `Contact`
* Use better taglines and content for the contact page.

**Comment by iadeelzafar** [comment]
@saadpasta Good work on the repo. I thought I could put in my part too. Will make a PR soon!

**Comment by saadpasta** [comment]
@iadeelzafar Thank you so much for the review hope to see your merge request soon

**Comment by kartikch918** [comment]
Hey I'm working on this issue. Will open a request soon. @saadpasta
