### ISSUE TITLE
Performance Issue 

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#82]
Currently, there is a performance issue on our DeveloperFolio we want it to load instantly. Currently, we are using lots of images from unDraw. 

This audit is done on saadpasta.github.io. Please try to do an audit on your portfolio.

<img width="795" alt="Screen Shot 2020-04-08 at 2 18 52 PM" src="https://user-images.githubusercontent.com/23307811/78767842-8f0fdb80-79a4-11ea-8c8e-9e280228ab60.png">
<img width="754" alt="Screen Shot 2020-04-08 at 2 19 02 PM" src="https://user-images.githubusercontent.com/23307811/78767864-90d99f00-79a4-11ea-96ac-82a71b7b1d7d.png">
<img width="745" alt="Screen Shot 2020-04-08 at 2 19 09 PM" src="https://user-images.githubusercontent.com/23307811/78767865-91723580-79a4-11ea-96f0-c4db91076eaa.png">

**Comment by saadpasta** [comment]
@kartik918

**Comment by kartik918** [comment]
Wow, I did not expect our app to be that big. I'll look into this and provide a fix ASAP.

![audit png](https://user-images.githubusercontent.com/48270786/78797175-fb0a3800-79d4-11ea-8b45-fb4471e02c66.jpg)

**Comment by kartik918** [comment]
I can't seem to find the "other" files responsible for this. Are you sure it's because of unDraw graphics? Because they're SVGs and they are in KBs so that can't be the reason. 
I see some room for optimizations to reduce 6-7 MBs but still don't know what is taking 40 MB of traffic.

**Comment by saadpasta** [comment]
@kartik918  I guess it's the images we our getting from other location that can be also an issue

**Comment by kartik918** [comment]
All the images are locally served from the assets folder as far as I know. 

We can remove the "portfolio.gif" from the repository and upload it to GitHub so that can save 7mb of repo space. 

Still not sure about the other 33 mbs.

**Comment by saadpasta** [comment]
No some images we are getting from urls

**Comment by kartik918** [comment]
I did more investigation on this and it seems the audit probably download the whole repo or something while accounting for factors involved in the test. The detailed browser network panel says otherwise.

![{AD2D25CD-95BE-4727-9434-C203D0823CAC} png](https://user-images.githubusercontent.com/48270786/78831422-3de50380-7a07-11ea-9cf3-844c7edb9cd4.jpg)

**Comment by kartik918** [comment]
I'm closing this issue for now since there are no newer reports of performance issues. 
This issue was also addressed by #94.
