### ISSUE TITLE
New contacts section #2

### ISSUE THREAD

**Issue by kartik918** [saadpasta/developerFolio#85]
LinkedIn offers a profile card display on a portfolio or any website. What do you think about redesigning contacts section or something like that if we want to include this in our portfolio.

[LinkedIn Cards](https://www.linkedin.com/pulse/how-create-linkedin-badge-your-website-brynne-tillman/)

**Comment by saadpasta** [comment]
@kartik918 I was thinking about exactly the same but with the Github. We could add Github Badge also that would be pretty cool 😀

**Comment by kartik918** [comment]
Haha it would certainly give more life to the contacts section that how it looks right now. Does Github have a similar card like structure or do we plan to design our own?

**Comment by saadpasta** [comment]
I don't know but we could use something like this 
<img width="396" alt="Screen Shot 2020-04-17 at 12 59 51 PM" src="https://user-images.githubusercontent.com/23307811/79546162-5f9b5600-80ab-11ea-8c37-8bcc6dc33603.png">

**Comment by kartik918** [comment]
This is a Github Badge and not exactly a card, but yeah we could think of reinventing the contacts section with a mix of all these ideas. 
Could use some help from an experienced UX designer to come up with a nice layout or mock to build from.
If no one offers to contribute for designs, we can come up with one ourselves.

**Comment by naveen521kk** [comment]
@kartik918 Can we add a GitHub card like .[This.](https://github.dev/) 
https://github.dev/
This looks clean 👌 and perfect.

**Comment by kartik918** [comment]
Looks great, good find! We could use the design from the left portion of the screenshot. We only need details like the Name, Place and Followers of a profile since we already fetch repo information. 

And because we already do have SSH keys of a profile, fetching this information would be relatively easier compared to designing the card. I might come up with a rough wireframe for direction if I get the time.

Let me know if you have any more ideas to add onto the design.

**Comment by naveen521kk** [comment]
@kartik918 I have done the API part of the Profile of Github. Help me out on the design and I planned of using ![Bootstrap Cards](https://react-bootstrap.github.io/components/cards/). Do you have any better Idea?

**Comment by kartik918** [comment]
Hey @naveen521kk , thanks for taking this up. I'm sorry I've been busy these days, I'll come up with a mock design to help you out for the card layout in a day or two. We can put your fork on hold till then.

The API integration seems to work fine but the layout could use a fresh and different face (We should make it unique I think and not a plain Bootstrap card). Also, how did you get the "Hireable" information, is it static, meaning it has to be entered manually? 

I think we could fit this all in a new layout for contacts sections with a completely new design. We can either go with a 3 card design or a more free form style. I'll explain my vision better through a mockup soon. 

Thanks and I'll send the design direction soon.

**Comment by kartik918** [comment]
And since the original codebase doesn't use Bootstrap , we shouldn't add a new dependency for a single card component. Less dependencies is always better and faster.

**Comment by naveen521kk** [comment]
@kartik918 The Hireable section is available in the Github API. So it's not entered manually and done through Github.

**Comment by kartik918** [comment]
Oh yes, I forgot that GitHub asks for that information too. I'll start on the designs later today.

**Comment by naveen521kk** [comment]
How about the design is it ready? @kartik918

**Comment by kartik918** [comment]
Here's a mock of what I have in mind. 

- The current portfolio lacks an image of the person so we can take their GH avatar for it.
- We can re-use the contact strip again instead of creating new buttons for the same.
- The location and job opportunity information can again be used from the GH profile (although we should give an option to set it manually).
- Add GH bio for "introduction" to the contact section.
- The component should flex and break into a column on smaller viewports.


![mock](https://user-images.githubusercontent.com/48270786/80600203-ad1fa780-8a49-11ea-8ff0-cb679daf549a.png)


(P.S use the same font i.e Montserrat for text and headers, I didn't have it so I had to use another)

Let me know what you think too @saadpasta !

**Comment by naveen521kk** [comment]
And are you gonna do or should I?

**Comment by saadpasta** [comment]
@kartik918 it looks great

**Comment by kartik918** [comment]
I'm really swarmed with work these days so I would appreciate if you would like to take this up @naveen521kk. We can leave it for another contributor too if you're busy. 
Thanks.

**Comment by naveen521kk** [comment]
So I have done some of the work and I get [this](https://mknaveen.netlify.app/). You can check whether I can make a PR.

**Comment by kartik918** [comment]
This looks great but we need to change some things like,

- Move the image to further right,
- Make the white image border to ``#6c63ff`` so it's consistent with the theme,
- Add ``transition: 0.3s all`` to shadow effects onHover,
- Reduce the font sizes so it doesn't look cluttered and make the component bigger if you have to, it's better than a small space.

Also, while you're at it, keep this component switchable. That is if someone doesn't have a Github or doesn't want to share it, they aren't forced to do it or have a blank space in their portfolio. So keep it switchable between the old one too.

You're doing good work, thanks!

**Comment by naveen521kk** [comment]
@kartik918 I have done what you asked for. Still need any other thing to do or shall I open a PR. Check out my test [deploy.](https://mknaveen.netlify.app/)

**Comment by kartik918** [comment]
This is neat!

Still some changes left to address,

- Left align all component text
- I opened this on my phone and the image isn't responsive. Adjust image size accordingly 
- Increase padding between contact links strip and the text
-  Reverse on hover shadow for the image, so the shadow goes away on hover and give a card-ish feel. Also, darker shadows (check blog card shadow css).

Also I see a ``<br>`` between ``desc-prof`` and ``social-media-div``, could you explain why it's there because it adds no change to the component? You should remove it if it's an error.

I hope you've also taken into account that this should be toggle-able with the old design.

And make a PR for this, it'll make my reviews easier. Thanks!

**Comment by naveen521kk** [comment]
@kartik918 I think I have done with it. Further, I have changed the app theme colour ` #6c63ff` as that previously black. I am opening a PR where you can further Review. For now, the test deploy is [here](https://mknaveen.netlify.app/). I am added enlarging effect on hover for the image.
