### ISSUE TITLE
Change Talks and Blog Section Design 

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#88]
I think currently our talk section is overwhelmed and we should change the design to something minimalist. We could take inspiration from this [site](https://ahmadawais.com/talks/ )

**Comment by saadpasta** [comment]
Blog Section Design Inspiration 
https://joshwcomeau.com/tutorials/

**Comment by kartik918** [comment]
Closing this, design has been updated in #90 and #32.
