### ISSUE TITLE
Rename of dockerFile to Dockerfile

### ISSUE THREAD

**Issue by rakesh-kadam** [saadpasta/developerFolio#89]
**I tried running the following command to:** 

`docker build -t developerfolio:latest .`

**But ran into following error:**

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/rakesh/Desktop/Projects/developerfolio/Dockerfile: no such file or directory

**Issue:** Dockerfile has wrong name. It is dockerFile instead of Dockerfile. Renaming the file successfully built my Docker container.

**Comment by saadpasta** [comment]
Thanks , Would like to make a PR for that

**Comment by kartik918** [comment]
Fixed in #98
