### ISSUE TITLE
Achievement Card Subtitle Not Working

### ISSUE THREAD

**Issue by aashutosh24** [saadpasta/developerFolio#95]
Inside Portfolio>achievementSection>achivementsCards>description i wrote all the descriptions but did not appear.

Just change **description** to **subtitle** and it works.

Thanks @saadpasta for this awesome template ❤

**Comment by saadpasta** [comment]
Thanks for the issue 😀This has been solved in #96

**Comment by aashutosh24** [comment]
Perfect 🎉
